### ISSUE TITLE
Docker build error invalid argument "*****/repo:latest" for "-t, --tag" flag: invalid reference format

### ISSUE THREAD

**Issue by nimishmistry** [CircleCI-Public/aws-ecr-orb#112]
### Orb version

6.12.2

### What happened

Step build-and-push-image fails during creation of docker image

````
#!/bin/bash -eo pipefail
registry_id=$(echo $AWS_ECR_ACCOUNT_URL | sed "s;\..*;;g")
number_of_tags_in_ecr=0

docker_tag_args=""
IFS="," read -ra DOCKER_TAGS <<< "latest,$CIRCLE_BUILD_NUM"
for tag in "${DOCKER_TAGS[@]}"; do
  if [ "false" = "true" ]; then
    docker_tag_exists_in_ecr=$(aws ecr describe-images --registry-id $registry_id --repository-name repo --query "contains(imageDetails[].imageTags[], '$tag')")
    if [ "$docker_tag_exists_in_ecr" = "true" ]; then
      docker pull $AWS_ECR_ACCOUNT_URL/repo:${tag}
      let "number_of_tags_in_ecr+=1"
    fi
  fi
  docker_tag_args="$docker_tag_args -t $AWS_ECR_ACCOUNT_URL/repo:$tag"
done
if [ "false" = "false" ] || [ "false" = "true" -a $number_of_tags_in_ecr -lt ${#DOCKER_TAGS[@]} ]; then
  docker build \
     \
    -f ./Dockerfile \
    $docker_tag_args \
    .
fi

invalid argument "****************************************************/repo:latest" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.

Exited with code exit status 125
````
### Config
````
version: 2.1

orbs:
    aws-ecr: circleci/aws-ecr@6.12.2

workflows:
    build-and-deploy:
        jobs:
            - aws-ecr/build-and-push-image:
                create-repo: true
                repo: repo
                tag: 'latest,$CIRCLE_BUILD_NUM'
````

### Expected behavior

Docker image should be successfully created.

**Comment by unamashana** [comment]
@nimishmistry Make sure you aren't using https in the value for AWS_ECR_ACCOUNT_URL. It should work without https.

**Comment by DrewTittle** [comment]
I am also having this issue, the AWS_ECR_ACCOUNT_URL env var doesn't have an http or https prefix but works fine for me.

The problem I'm seeing is when one of the tags has a / in it. I am trying to tag with the git branch and anytime the branch is feature/blabla I get this error.

**Comment by rusowyler** [comment]
@DrewTittle in AWS_ECR_ACCOUNT_URL don't add the ending / neither the protocol. For example: "XXXXXXXXXXXX.dkr.ecr.us-east-2.amazonaws.com"

**Comment by jcity** [comment]
If you remove the quotes from the tag property, it should work. At least it does in version `7.3.0`

```
version: 2.1

orbs:
    aws-ecr: circleci/aws-ecr@7.3.0

workflows:
    build-and-deploy:
        jobs:
            - aws-ecr/build-and-push-image:
                create-repo: true
                repo: repo
                # Make sure these aren't surrounded by quotes
                tag: latest,$CIRCLE_BUILD_NUM
```
