### ISSUE TITLE
Allow passing DockerHub credentials to build-and-push-image job

### ISSUE THREAD

**Issue by blimmer** [CircleCI-Public/aws-ecr-orb#114]
## What would you like to be added

It would be nice to have a way to easily run a `docker login` command as part of the `build-and-push-image` job.

## Why is this needed

Starting November 1, 2020, DockerHub will [begin rate-limiting image pulls from DockerHub](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/). In my case, we need DockerHub access to build our image before we push it to ECR.

## Workaround

Since the `build-and-push-image` job is also exposed as a command, I can also work around this problem like this. However, I have a feeling that having parameters exposed for this could be handy for folks once the rate limit is in effect.

```yaml
build-and-push-image:
  # Use upstream default machine executor
  # https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/executors/default.yml
  machine:
    image: ubuntu-1604:201903-01
  steps:
    - run:
        name: Docker login
        command: docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_ACCESS_TOKEN
    - aws-ecr/build-and-push-image:
        repo: "my-repo"
        tag: "my-service-${CIRCLE_SHA1},my-service-latest"
```
