### ISSUE TITLE
tag invalid reference format

### ISSUE THREAD

**Issue by andrzpg12** [CircleCI-Public/aws-ecr-orb#125]
### Orb version 6.15.0

This is my config file for build

```
  build-and-push-ecr:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: ECR_REGISTRY
          repo: test-automation
          region: AWS_REGION
          tag: '$CIRCLE_SHA1, latest'
          filters:
            branches:
              only:
                - main
                - push-image
```

The environment variables are: ECR_REGISTRY, AWS_REGION.

What is wrong in my job, anything i tried is returning: 

```
invalid argument "********************************************/************************:" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.

Exited with code exit status 125
CircleCI received exit code 125
```

**Comment by andrzpg12** [comment]
i need to tag my images always with "latest" and the CIRCLE_SHA1...
also i need to build-arg with 2 environment variables.. how is the correct syntax? is not enough claire in the doc

**Comment by elia** [comment]
Have you tried removing the space after the comma? `tag: '$CIRCLE_SHA1,latest'`

**Comment by andrzpg12** [comment]
yeah, after that i just delete $CIRCLE_SHA1 tag and work, but my question is if supports multiple tags, and how is the syntax of that.

**Comment by LLemeLopes** [comment]
> Have you tried removing the space after the comma? `tag: '$CIRCLE_SHA1,latest'`

For me, this worked.

**Comment by brivu** [comment]
Closing this issue for now.  Please let me know if this is still a problem

**Comment by vmrvictor** [comment]
for me is still a problem I have upgraded from 7.0.0 to 9.0.2
```
      - aws-ecr/build_image:
          account_id: ${AWS_ACCOUNT_ID_X}
          path: myPath
          repo: myRepo
          tag: '${CIRCLE_SHA1},latest'
```
but then it is ERROR: invalid tag "************.dkr.ecr..amazonaws.com/myRepo:longcommitHash": invalid reference format
