### ISSUE TITLE
Support for layer caching?

### ISSUE THREAD

**Issue by jeffnappi** [CircleCI-Public/aws-ecr-orb#14]
Would be great to have this Orb support https://circleci.com/docs/2.0/docker-layer-caching/

**Comment by jeffnappi** [comment]
I see that this can be accomplished via `executors`. Closing this issue, but for anyone looking for information on this you simply need to enable docker_layer_caching in an executor in order to enable it.

**Comment by ericf89** [comment]
@jeffnappi  Is this possible at the job level, or only by command?  Still trying to figure out the syntax :/

**Comment by jeffnappi** [comment]
@ericf89 At the top of your `.circleci/config.yml` you need to define the executor:
e.g.
```
orbs:
  aws-ecr: circleci/aws-ecr@3.0.0
executors:
  docker_build:
    machine:
      docker_layer_caching: true
```

Then in your workflow job you can specify the executor:
```
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          executor: docker_build
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          context: myContext
          create-repo: true
          dockerfile: myDockerfile
          path: pathToMyDockerfile
          profile-name: myProfileName
          region: AWS_REGION_ENV_VAR_NAME
          repo: myECRRepository
          tag: myECRRepoTag
```

My understanding is that Orbs can only be used within workflows.
