### ISSUE TITLE
Cannot perform an interactive login from a non TTY device

### ISSUE THREAD

**Issue by rj93** [CircleCI-Public/aws-ecr-orb#144]
### Orb version
7.0.0

### What happened
Attempting to use the aws-ecr/ecr-login command but I am getting the error:
```
An error occurred (AccessDeniedException) when calling the GetAuthorizationToken operation: User: arn:aws:iam:... is not authorized to perform: ecr:GetAuthorizationToken on resource: *
Error: Cannot perform an interactive login from a non TTY device
```

I suspected this was because I was using a docker executor, but I tried changing the job use a machine but it still has the same issue.

Docker:
```
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.0.0

jobs:
  // other jobs to checkout code, etc
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - setup_remote_docker
      - run:
           name: Build docker image
           command: // a command to build the docker image using maven
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: nominee-api
          tag: '${RELEASE_VERSION},latest'

workflows:
  my-build:
    jobs:
      - checkout-code
      - build:
          requires: 
            - checkout-code
```

Machine:
```
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.0.0

jobs:
  // other jobs to checkout code, etc
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
           name: Build docker image
           command: // a command to build the docker image using maven
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: nominee-api
          tag: '${RELEASE_VERSION},latest'

workflows:
  my-build:
    jobs:
      - checkout-code
      - build:
          requires: 
            - checkout-code
```

### Expected behavior
It should log in successfully.
