### ISSUE TITLE
Problem with extra-build-args in aws-ecr/build-and-push-image

### ISSUE THREAD

**Issue by alex-hladun** [CircleCI-Public/aws-ecr-orb#146]
### Orb version
circleci/aws-ecr@7.0.0

### What happened

![image](https://user-images.githubusercontent.com/57810269/121072415-6d6bd900-c78e-11eb-960f-56708a4ad857.png)

My config:
```
- aws-ecr/build-and-push-image:
          context: CIRCLE
          requires:
            - Build react app
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          path: ./server
          region: AWS_REGION
          repo: my-socket-app-repo
          tag: "latest"
          attach-workspace: true
          extra-build-args: "--secret id=aws,src=$~/.aws/credentials ."
```
### Expected behavior

Should build with secrets file

**Comment by JalexChen** [comment]
Hi @alex-hladun,

If I'm understanding what you're trying to do here, it's to utilize a Dockerfile within a hidden/secrets directory.

If so, the path should only be prefixed with "." and the docker build and configuration should reflect that as well

```
docker build \
 --secret id=aws, src=$~/ .aws/credentials . \
 -f Dockerfile \ 
 # the default for -f within the orb is to utilize the specified path, which would result in .server/Dockerfile, so adding it here 
 isn't necessary
 $docker_tag_args \
 .server
```

```
path: .server
```

Please feel free to re-open the issue if this doesn't address the problem

**Comment by brivu** [comment]
Hey @alex-hladun, 

I'm Brian from CircleCI's CPE team.  I just want to understand the issue you're running into a little more so I can see if this can be resolved for you.  

When you say the command should build with a secret file, what are you referring to?  Are you saying that `./server ` is a hidden directory where the `Dockerfile` is stored?  If so, a hidden directory should be `.server`. 

I tested this on my end storing the `Dockerfile` into a directory called `.hidden` and it all works.  Check out my config below: 

```
      - aws-ecr/build-and-push-image:
          name: integration-tests-default-profile
          attach-workspace: true
          workspace-root: workspace
          repo: aws-ecr-orb-${CIRCLE_SHA1:0:7}-default-profile
          create-repo: true
          tag: integration,myECRRepoTag
          dockerfile: .hidden/Dockerfile
          extra-build-args: --compress
          post-steps:
            - run: aws ecr delete-repository --repository-name aws-ecr-orb-${CIRCLE_SHA1:0:7}-default-profile --force
          executor: ubuntu
          requires: [pre-integration]
```  

I'm closing this issue for now but please feel free to reopen if this isn't helpful.  

Best, 
Brian
