### ISSUE TITLE
Add multi-region example

### ISSUE THREAD

**Issue by glenwinters** [CircleCI-Public/aws-ecr-orb#147]
## What would you like to be added

It would be nice to have an example for building an image and pushing it to multiple ECRs (e.g. in different regions).

## Why is this needed

It's not immediately obvious how to do this because the docker login, build, tag, and push are bundled together. Even using the sub-commands, I don't think you can tag the image with two separate full ECR URLs without building twice.

**Comment by brivu** [comment]
Hey @glenwinters, 

I'm doing a major update of this orb which includes removing the `account-url` parameter and replacing it with `registry-id`.  With this parameter in place, we can construct the registry URLs like below: 

``` ${REGISTRY_ID}.dkr.ecr.${REGION}.amazonaws.com``` 

I have also made the `region` parameter a `string` instead of an environment variable.  This way, you'll be able to use a matrix build in order to build and push to multiple regions.  

However, as you pointed out, this will involve building images multiple times because you'd have to log into each region first and before you can build/push each image.  

Here's an example below: 

```
 - aws-ecr/build-and-push-image:
          repo: aws-ecr-orb-multi-region<<matrix.region>>
          tag: integration,myECRRepoTag
          dockerfile: sample/Dockerfile
          platform: linux/arm64
          matrix:
            parameters:
              region: ["us-west-2","us-west-1"]
          executor: arm64
```

I know that's not exactly what you wanted but hopefully with the new parameters, it'll give you more flexibility.  Thanks for your contribution!

Best, 
Brian
