### ISSUE TITLE
Docker Layer Caching not working with arm64 machine executor

### ISSUE THREAD

**Issue by innomatics** [CircleCI-Public/aws-ecr-orb#148]
### What happened

Am running a performance plan with a machine executor (arm.medium).  Have tried to configure DLC in the executor and job, but the cached layers aren't being used in my builds.

The DLC credits are being deducted in my plan usage :(

### Expected behavior

When re-running a build I should see messages
```
 ---> Using cache
```

### Representative config
```
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
executors:
  arm-executor:
    machine:
      docker_layer_caching: true
      image: 'ubuntu-2004:202101-01'
    resource_class: arm.medium
jobs:
  build-and-push-image:
    executor: arm-executor
    steps:
      - aws-ecr/build-and-push-image:
          repo: example-repo
          remote-docker-layer-caching: true # have also tried without this - same result
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build-and-push-image
```

**Comment by innomatics** [comment]
Bumping as this is still an issue for us

CircleCI support have emailed me a few times times that it's fixed but it doesn't work for my account on this example repo: https://github.com/the-volte/dlc 

@iynere or anyone if you have time to reproduce it might help move things along.

**Comment by treharne** [comment]
+1
I am experiencing the same bug.
Similar setup to @innomatics with 
```
   machine:
      docker_layer_caching: true
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
```

only material difference is that we don't use the ECR orb, we perform that step manually.

Keen to know if this is being worked on?
