### ISSUE TITLE
Add param build-context-path in build image

### ISSUE THREAD

**Issue by ishii1648** [CircleCI-Public/aws-ecr-orb#161]
## What would you like to be added

I want to add build-context-path parameters to support Dockerfile that is no located in root directory.

## Why is this needed

I often located Dockerfile in no root directory like bellow.

```
cmd
├── example01
│   ├── Dockerfile
│   └── main.go
└── example02
    ├── Dockerfile
    └── main.go
```

I can't build docker images in this case, because there is only path parameters(Path to the directory containing your Dockerfile and build context) in aws-ecr-orb.

I want to add build-context-path parameters to set build context path separately from path containing Dockerfile.

```yaml
docker build \
  <<#parameters.extra-build-args>><<parameters.extra-build-args>><</parameters.extra-build-args>> \
  -f <<parameters.path>>/<<parameters.dockerfile>> \
  $docker_tag_args \
  <<parameters.path>> <-- should be able to set another parameter!
```

**Comment by samay023** [comment]
@ishii1648 
What I ended up doing as a workaround is

`````
- aws-ecr/build-and-push-image:
          dockerfile: projects/abc/Dockerfile

- aws-ecr/build-and-push-image:
          dockerfile: projects/bcd/Dockerfile
`````
