### ISSUE TITLE
An error occurred (UnrecognizedClientException) when calling the GetAuthorizationToken operation: The security token included in the request is invalid. Error: Cannot perform an interactive login from a non TTY device 

### ISSUE THREAD

**Issue by Bash-mocart** [CircleCI-Public/aws-ecr-orb#163]
### Orb version
circleci/aws-ecr@7.2.0

### What happened

Log into Amazon ECR in the workflow aws-ecr/build-and-push-image isnt passing

### Expected behavior
Should be able to run without any trouble

**Comment by yaningo** [comment]
Hi, @Bash-mocart, were you using the default executor for the `aws-ecr/build-and-push-image` job?

If you don't specify an `executor` (https://circleci.com/developer/orbs/orb/circleci/aws-ecr#jobs-build-and-push-image), it'll use the [default one](https://circleci.com/developer/orbs/orb/circleci/aws-ecr#executors-default) which has AWS CLI `v2.0.52` installed.

As per the [AWS CLI command reference](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecr/get-login-password.html) `get-login-password` is supported using the latest version of AWS CLI version 2 or in v1.17.10 or later of AWS CLI version 1, but it's not clear which exact version 2 started supporting it.

**Comment by yuichiro12** [comment]
Hi.
I tried with non-default executor and I found it still happens in circleci/aws-ecr@>=v7.0.0.

The workaround is using `override-installed` in aws-cli orb:

```yaml
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.0
  aws-ecr: circleci/aws-ecr@7.0.0
executors:
  docker_build:
    machine:
      docker_layer_caching: true
...
jobs:
  build-and-push-image:
    executor: docker_build
    steps:
      - checkout
      - aws-cli/setup:
          override-installed: true
      - aws-ecr/build-and-push-image:
      ...
```

`get-login-password` is added in aws-cli v2.0.0, so any awscli v2 will do.
FYI: 
https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst#200
