### ISSUE TITLE
Add a command to tag (and push) existing images

### ISSUE THREAD

**Issue by Maxwell2022** [CircleCI-Public/aws-ecr-orb#166]
## What would you like to be added

The same way [the GCP orb](https://circleci.com/developer/orbs/orb/circleci/gcp-gcr#usage-tag-existing-image) is tagging and existing image and pushing the tag (without having to build or run custom docker command)
```
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/tag-image:
          context: myContext
          image: my-image
          source-tag: mytag1
          target-tag: mytag2
```

## Why is this needed

1. One way to tag with the current orb is to rebuild the image which doesn't really make sense
2. Another way is to use docker command but then the visibility is not great with `$AWS_ECR_ACCOUNT_URL` prefix etc
3. Easy switch between orbs (using the same API)
