### ISSUE TITLE
Docker layer caching not working

### ISSUE THREAD

**Issue by AkashHC13** [CircleCI-Public/aws-ecr-orb#171]
### Orb version
7.3.0

### What happened

Below is my circleCI workflow to build and push aws ecr image.
```yml
workflows:
  version: 2.1
  deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_DEV
          dockerfile: Dockerfile.prod
          no-output-timeout: 20m
          repo: "${AWS_REPO_NAME_DEV}"
          remote-docker-layer-caching: true
          tag: "${CIRCLE_SHA1}"
          executor:
            name: aws-ecr/default
            use-docker-layer-caching: true
```
We have performance plan and hence DLC is enabled for us. Although its enabled, the build step is not cached at all. Every time it runs for about 5 mins.
I also tried to set `setup-remote-docker:` to true. But that doesn't help either. I see a different error
![image](https://user-images.githubusercontent.com/21243624/149018449-a55addaf-1e00-4dd7-90ef-3eb0da14ab2b.png)

### Expected behavior
As per the documentation, with docker layer caching enabled and `remote-docker-layer-caching` set to true, the build time should be faster with caching.

**Comment by JalexChen** [comment]
Hi @AkashHC13, 

Based off your error, it looks like you're trying to utilize both a machine executor in addition to a remote docker in the same step or command. The remote docker should be separate from the machine executor; these are two different executors altogether and would need to be specified as separate entities. Are you looking to run a job specifically on a VM, or would you be fine with a remote docker? You can also do both, but they would need to be specified differently; example provided below:

```
executors:
  linux:
    docker:
      - image: cimg/base:stable
  steps:
      - setup_remote_docker:
          version: "20.10.11"
          docker_layer_caching: true
  macos:
    macos:
      xcode: 13.2.0
  machine:
    machine:
      image: ubuntu-2004:202111-01
      docker_layer_caching: true
```

Additionally, it's important to note that DLC has limitations per the docs [here](https://circleci.com/docs/2.0/docker-layer-caching/)

I'd need additional information, such as which image you're using, but perhaps this might be applicable to your case:

> DLC is only useful when creating your own Docker image with docker build, docker compose, or similar docker commands, it does not decrease the wall clock time that all builds take to spin up the initial environment.

For example, if you're using one of our convenience images, these are already cached and should be accessible in the least amount of time. However, if you are using an image you'll need to build, then DLC would certainly work if set to true.
