### ISSUE TITLE
Support environment variable for source-tag in tag-image job

### ISSUE THREAD

**Issue by gobbledygook88** [CircleCI-Public/aws-ecr-orb#181]
## What would you like to be added

The `tag-image` job supports `source-tag` as a parameter. Unfortunately, it seems the following configuration doesn't work as intended.

```yml
tag_image:
    executor: python
    steps:
      - aws-cli/setup
      - aws-ecr/tag-image:
          repo: "${ECR_REPO}"
          source-tag: "${CIRCLE_SHA1}"
          target-tag: "latest"
```

Looking at the source code, the `repo` parameter is evaluated but `source-tag` isn't.
It would be nice to have `source-tag` evaluated too.

Happy to raise a PR if this is something we'd like to support.
