### ISSUE TITLE
error: failed to solve: failed to read dockerfile on v8.0.0

### ISSUE THREAD

**Issue by hshafy** [CircleCI-Public/aws-ecr-orb#185]
### Orb version
v8.0.0

### What happened
One of our repos had this error of not finding dockerFile on the `Build docker image with buildx` step.

In this worfklow we use the `build-image` command, this error is not repreducable in other repos, going back to v7.3.0 and using `build-and-push-image` command instead without changing anything else fixes it!

```
#!/bin/bash -eo pipefail
#!/bin/bash
REPO=$(eval echo "${PARAM_REPO}")
REGION=$(eval echo "${PARAM_REGION}")
TAG=$(eval echo "${PARAM_TAG}")
ACCOUNT_URL="${!PARAM_REGISTRY_ID}.dkr.ecr.${REGION}.amazonaws.com"
ECR_COMMAND="ecr"
number_of_tags_in_ecr=0
docker_tag_args=""

IFS="," read -ra PLATFORMS <<<"${PARAM_PLATFORM}"
arch_count=${#PLATFORMS[@]}

if [ "${PARAM_PUBLIC_REGISTRY}" == "1" ]; then
  if [ "$arch_count" -gt 1 ]; then
    echo "AWS ECR does not support multiple platforms for public registries. Please specify only one platform and try again"
    exit 1
  fi

  ECR_COMMAND="ecr-public"
  ACCOUNT_URL="public.ecr.aws/${!PARAM_REGISTRY_ID}"
fi

IFS="," read -ra DOCKER_TAGS <<<"${TAG}"
for tag in "${DOCKER_TAGS[@]}"; do
  if [ "${PARAM_SKIP_WHEN_TAGS_EXIST}" = "1" ]; then
    docker_tag_exists_in_ecr=$(aws "${ECR_COMMAND}" describe-images --profile "${PARAM_PROFILE_NAME}" --registry-id "${!PARAM_REGISTRY_ID}" --region "${REGION}" --repository-name "${REPO}" --query "contains(imageDetails[].imageTags[], '${tag}')")
    if [ "${docker_tag_exists_in_ecr}" = "1" ]; then
      docker pull "${ACCOUNT_URL}/${REPO}:${tag}"
      number_of_tags_in_ecr=$((number_of_tags_in_ecr += 1))
    fi
  fi
  docker_tag_args="${docker_tag_args} -t ${ACCOUNT_URL}/${REPO}:${tag}"
done

if [ "${PARAM_SKIP_WHEN_TAGS_EXIST}" = "0" ] || [[ "${PARAM_SKIP_WHEN_TAGS_EXIST}" = "1" && ${number_of_tags_in_ecr} -lt ${#DOCKER_TAGS[@]} ]]; then
  if [ "${PARAM_PUSH_IMAGE}" == "1" ]; then
    set -- "$@" --push
  fi

  if [ -n "$PARAM_EXTRA_BUILD_ARGS" ]; then
    set -- "$@" "${PARAM_EXTRA_BUILD_ARGS}"
  fi

  if [ "${PARAM_PUBLIC_REGISTRY}" == "1" ]; then
    docker buildx build \
      -f "${PARAM_PATH}"/"${PARAM_DOCKERFILE}" \
      ${docker_tag_args} \
      --platform "${PARAM_PLATFORM}" \
      --progress plain \
      "$@" \
      "${PARAM_PATH}"
  else
    docker context create builder
    docker run --privileged --rm tonistiigi/binfmt --install all
    docker --context builder buildx create --use
    docker --context builder buildx build \
      -f "${PARAM_PATH}"/"${PARAM_DOCKERFILE}" \
      ${docker_tag_args} \
      --platform "${PARAM_PLATFORM}" \
      --progress plain \
      "$@" \
      "${PARAM_PATH}"
  fi
fi

builder
Successfully created context "builder"
Unable to find image 'tonistiigi/binfmt:latest' locally
latest: Pulling from tonistiigi/binfmt

0e08bd75: Pulling fs layer 
Digest: sha256:5bf63a53ad6222538112b5ced0f1afb8509132773ea6dd3991a197464962854e
Status: Downloaded newer image for tonistiigi/binfmt:latest
installing: riscv64 OK
installing: arm OK
installing: ppc64le OK
installing: mips64le OK
installing: mips64 OK
installing: arm64 OK
installing: s390x OK
{
  "supported": [
    "linux/amd64",
    "linux/arm64",
    "linux/riscv64",
    "linux/ppc64le",
    "linux/s390x",
    "linux/386",
    "linux/mips64le",
    "linux/mips64",
    "linux/arm/v7",
    "linux/arm/v6"
  ],
  "emulators": [
    "jar",
    "llvm-10-runtime.binfmt",
    "python2.7",
    "python3.8",
    "qemu-aarch64",
    "qemu-arm",
    "qemu-mips64",
    "qemu-mips64el",
    "qemu-ppc64le",
    "qemu-riscv64",
    "qemu-s390x"
  ]
}
flamboyant_curran
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 3.3s done
#1 creating container buildx_buildkit_flamboyant_curran0
#1 creating container buildx_buildkit_flamboyant_curran0 1.3s done
#1 DONE 4.6s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 2B done
#2 DONE 0.0s
error: failed to solve: failed to read dockerfile: open /tmp/buildkit-mount921181307/Dockerfile: no such file or directory

Exited with code exit status 1
CircleCI received exit code 1
```

### Expected behavior

Build and push image with v8.0.0 just like the v7.3.0

**Comment by brivu** [comment]
Hey @hshafy, 

Can you show my your config? I think there might be an issue with the way you're using the `path` parameter and the `dockerfile` parameter. 

Best, 
Brian

**Comment by brivu** [comment]
Hi @hshafy, 

Just wanted to check in to see if this is still an issue for you. Let me know so I can help get this sorted out.

Best, 
Brian

**Comment by hshafy** [comment]
@brivu yes it's still an issue, had to move back to `v7.3.0`, here is my config file, please let me know I do something wrong!
```
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.0.0

jobs:
  push-staging:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    steps:
      - run:
          name: Get Short commit hash
          command: |
            echo 'export SHORT_SHA1=$(echo $CIRCLE_SHA1 | cut -c 1-7)' >> $BASH_ENV
            source $BASH_ENV
            echo "Short tag is: $SHORT_SHA1"
      - aws-ecr/build-image:
          repo: "my-repo"
          tag: "${SHORT_SHA1}"
  tag-prod-image:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    steps:
      - checkout
      - aws-ecr/ecr-login
      - run:
          name: tag image
          # aws-ecr/tag-image has this [issue](https://github.com/CircleCI-Public/aws-ecr-orb/issues/181) passing source tag , so implementing it manually until fixed
          command: |
            export SHORT_SHA1=$(echo $CIRCLE_SHA1 | cut -c 1-7)
            echo "Short tag is: $SHORT_SHA1"
            export MAN=$(aws ecr batch-get-image --repository-name my-repo --image-ids imageTag=$SHORT_SHA1 --query 'images[].imageManifest' --output text)
            echo "MAN is: $MAN"
            aws ecr put-image --repository-name my-repo--image-tag=$CIRCLE_TAG --image-manifest="$MAN"

workflows:
  pipeline:
    jobs:
      - push-staging:
          context:
            - context
          filters:
            branches:
              only: master
      - tag-prod-image:
          context:
            - context
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
```
