### ISSUE TITLE
Unable to copy files from host to Docker image

### ISSUE THREAD

**Issue by trulex** [CircleCI-Public/aws-ecr-orb#186]
### Orb version
8.0.0

### What happened
Docker build cannot find host files that needs to be copied into the image.
Build fails at **Build Docker Image with buildx**
```
#7 [2/2] COPY --chown=185 build/out.txt /tmp/
#7 sha256:3d71d3a51bad9719f03a9bc01bdc5909689e04c3b0d5c5dd5ca37cf7f1f5461b
#7 CANCELED
Dockerfile:3
--------------------
   1 |     FROM registry.access.redhat.com/ubi8/openjdk-17:1.11
   2 |     
   3 | >>> COPY --chown=185 build/out.txt /tmp/
   4 |     
--------------------
error: failed to solve: rpc error: code = Unknown desc = failed to compute cache key: failed to calculate checksum of ref iw117qcax6zv4wxxt4s15dpar::6dtat5r9ypotavr6wf8c8u0la: failed to walk /tmp/buildkit-mount1606104887/build: lstat /tmp/buildkit-mount1606104887/build: no such file or directory
```
Motivation is to preserve build files from a previous job without publishing them as artifacts since it's enough to just copy them into a Docker image in the job that comes after.

### Expected behavior
Host files are accessible.

### config.yml
```
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.0.0
  docker-orb: circleci/docker@2.0.3

jobs: # a collection of steps
  build:
    docker: # run the steps with Docker
      - image: cimg/openjdk:17.0 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - run:
          name: Prepare output files
          command: mkdir -p build/out && echo "hi" > build/out/out.txt
      - persist_to_workspace:
          root: build
          paths:
            - out/*
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - aws-ecr/build-and-push-image:
          requires:
            - build
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
          attach-workspace: true
          setup-remote-docker: true
          executor: docker-orb/docker

```

### Dockerfile
```
FROM registry.access.redhat.com/ubi8/openjdk-17:1.11

COPY --chown=185 build/out.txt /tmp/
```
