### ISSUE TITLE
Error: unknown flag: --use

### ISSUE THREAD

**Issue by luisdavim** [CircleCI-Public/aws-ecr-orb#188]
### Orb version

`circleci/aws-ecr@8.0`

### What happened

I've updated my configuration to use the latest version and now the step `Build a docker image with Docker Buildx` fails with the error: `unknown flag: --use`

### Expected behaviour

A docker image should be built without errors.

This is how I'm using the command:

```yaml
      - aws-ecr/build-and-push-image:
          context: my-organization-environment
          tag: $CIRCLE_SHA1
          skip-when-tags-exist: true
          repo: platform-tools
          no-output-timeout: 5m
          executor: aws-eks/python
          remote-docker-layer-caching: true
          setup-remote-docker: true
          remote-docker-version: 20.10.11
          extra-build-args: "--pull --build-arg bugsnag_key=$BUGSNAG_API_KEY --build-arg slack_releases_url=$SLACK_RELEASES_URL"
```

**Comment by brivu** [comment]
Hey @luisdavim, 

I've addressed this issue and it should be ready soon in PR #187. If you'd like to test these changes, you can change the version to `@dev:alpha` in your config and it should work.

Here's the link: https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:alpha

Can you give that a try and let me know if it works?

Best, 
Brian

**Comment by luisdavim** [comment]
Hi @brivu I've tried that and it fails exactly the same way:

```
unknown flag: --use
See 'docker --help'
```

**Comment by brivu** [comment]
Hey @luisdavim, 

That's really strange because I do not see a `--use` flag anywhere in your extra arguments at all.  Moreover, I'm not inject `--use` anywhere in this repo. 

Does the job show you the bash command it's trying to run?

One more thing to try, in my `config.yml` I am not using quotations in for the extra arguments:

```
      - aws-ecr/build-and-push-image:
          name: integration-tests-default-profile
          attach-workspace: true
          workspace-root: workspace
          repo: aws-ecr-orb-${CIRCLE_SHA1:0:7}-default-profile
          create-repo: true
          context: [CPE_ORBS_AWS]
          tag: integration,myECRRepoTag
          dockerfile: sample/Dockerfile
          path: workspace
          extra-build-args: --compress
          executor: amd64
```

Perhaps if you try removing it, it may make a difference?  

Let me know! 

Best, 
Brian

**Comment by brivu** [comment]
@luisdavim, 

I made a mistake.  The dev version is here: https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=dev:e4fb53122a1e1ea4e073ae413c7816b1e2f538de

Hoping that makes a difference. 

Best, 
Brian

**Comment by luisdavim** [comment]
Ok, I'll give it a go and let you know how it went. :+1

**Comment by luisdavim** [comment]
BTW the `--use` flag comes from your orb, in the `docker buildx` command, not from my args.

You can see it in the orb source in https://circleci.com/developer/orbs/orb/circleci/aws-ecr line 127.

**Comment by luisdavim** [comment]
I still get the same error with `dev:e4fb53122a1e1ea4e073ae413c7816b1e2f538de`

**Comment by luisdavim** [comment]
This is where the flag is in your branch: https://github.com/CircleCI-Public/aws-ecr-orb/blob/update-v8.1/src/scripts/docker-buildx.sh#L64

**Comment by luisdavim** [comment]
Hi, I did try using different docker versions but as mentioned in my original post I'm using `2.10.11` (remote docker setup).
I use private ECR repos to store my images and for the executer I use a custom image based off your `cimg/python:3.9.6` image.
I'm not cross compiling and I'm not building images for multiple achitectures, only Linux.

I tryied the command locally, using the latest docker client version and I get the same error.

**Comment by luisdavim** [comment]
@brivu I was able to make some progress by using a different image, I'm guessing the issue might have been the docker client version in the image I was using before but now I'm getting errors regarding my extra build args, regadless of using quotes or not it fails if I try to mass more than just a single art, I thik the prolem is that the script in this Orb uses `--set` and passes the args as a quoted env var, normally when using strings to construct commands to execute I end up having to use `eval`.

**Comment by brivu** [comment]
@luisdavim, the dev version of this orb should take care of that issue and then version 8.1 once this PR is merged.  

I removed the quotations and passed in multiple build args as a test and it works. Can you give it a try to let me know?

**Comment by luisdavim** [comment]
Hi @brivu I can confirm that your branch solves that issue. Thanks.

**Comment by eladitzhakian** [comment]
Hey @brivu, I've used the latest dev version of your branch and I'm still getting the `--use` error.

Config:
```
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@dev:f6748bd6ceb67658c100cb08f20cf3f0d83b76d1

executors:
  machine-large:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
      resource_class: large

workflows:
  build-and-push:
    jobs:
      - aws-ecr/build-and-push-image:
          executor: machine-large
          name: build-and-push-image
          repo: myrepo
          tag: "${CIRCLE_SHA1},latest"
          platform: linux/amd64,linux/arm64
```

**Comment by AntonCriterion** [comment]
The problem still persists at 8.1.2

```
    docker:
      - image: circleci/python:3.9
    steps:
...
      - aws-ecr/build-and-push-image:
          create-repo: true
          registry-id: ACCOUNT_ID
          region: AWS_DEFAULT_REGION
          repo: name
```
