### ISSUE TITLE
ecr-login does not login if .docker/config.json already exists

### ISSUE THREAD

**Issue by kochalex** [CircleCI-Public/aws-ecr-orb#189]
### Orb version

8.0.0

### What happened

* The `ecr-login` command did not log into AWS ECR when a dockerhub credential had been previously configured in a workflow.
  * The `ecr-login` command checks for the presence of `~/.docker/config.json` and assumes that ECR is configured.  It does not actually check if ECR credentials exist or are valid.

### Expected behavior

The login command should support authenticating docker to multiple registries, in any order.

**Comment by brivu** [comment]
Hey @kochalex, 

Can you show me an example of your config so I can take a look? I am not sure if this orb is set up to handle multiple logins. 


> * The `ecr-login` command checks for the presence of `~/.docker/config.json` and assumes that ECR is configured.  It does not actually check if ECR credentials exist or are valid.

This validation is meant to check and see if the user has a credential helper installed. If so, trying to log in with `ecr-login` will fail. 

I am not sure we can support multiple log in methods but I'm happy to take a look if you can give me an example of your use case. 

Let me know, 
Brian

**Comment by kochalex** [comment]
Sure - I am combining both the docker and ECS orbs to push to build and push to both ECR and dockerhub.  Here's a anonymized version of it that should show what's going on.  `docker/publish` creates the same config file too, causing `ecr-login` to not actually log into ECR.

Would there any harm if the orb re-ran the `aws ecr get-login-password ...` command when `aws-ecr/ecr-login` is invoked?

```yaml
version: 2.1
orbs:
  docker: circleci/docker@2.0.3
  aws-ecr: circleci/aws-ecr@8.0.0

workflows:
  build-and-publish:
    when:
      matches:
        pattern: "^main$"
        value: << pipeline.git.branch >>
    jobs:
      - docker/publish:
          image: dockerhub_org/repository_name
          tag: latest
          after_build:
            - aws-ecr/ecr-login
            # this step was added to work around the issue logged here
            - run:
                name: force login to ECR
                command: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin our_ecr_registry
            - run:
                name: add tag for ECR
                command: docker tag dockerhub_org/repository_name our_ecr_registry/repository_name:latest
            - run:
                name: push to ECR
                command: docker push our_ecr_registry/repository_name:latest
```
