### ISSUE TITLE
Access file generated by previous job?

### ISSUE THREAD

**Issue by gvolpe** [CircleCI-Public/aws-ecr-orb#19]
### Orb version

2.0.3

### What happened

I'm trying to deploy a Haskell application but I'm failing to copy the executable file from one job to the other. This is my CircleCI config file:

```yaml
version: 2.1

orbs:
  haskell: haskell-works/haskell-build@1.4.1
  aws-ecr: circleci/aws-ecr@2.0.3

workflows:
  build_and_publish_bill_statement_gen:
    jobs:
      - haskell/build:
          name: GHC 8.6.3
          executor: haskell/ghc-8_6_3
          cabal-file: bill-statement-gen.cabal
      - aws-ecr/build_and_push_image:
          requires: [GHC 8.6.3]
          context: staging-microservices
          region: AWS_DEFAULT_REGION
          repo: bill-statement-gen
          attach-workspace: true
```

And my `Dockerfile`:

```dockerfile
FROM quay.io/haskell_works/ghc-8.6.3

ADD /root/project/dist-newstyle/build/x86_64-linux/ghc-8.6.3/bill-statement-gen-0.1.0.0/x/bill-statement-gen-exe/build/bill-statement-gen-exe/bill-statement-gen-exe /usr/bin/bill-statement-gen-exe
ADD /root/project/config/app.dhall /config/app.dhall

CMD bill-statement-gen-exe
```

### Expected behavior

I'm not sure on whether `attach-workspace` is the option I'm looking for or not but I'd expect to have access to the executable file generated in the previous job `haskell/build`.

I get this error:

```
Step 2/5 : ADD /root/project/dist-newstyle/build/x86_64-linux/ghc-8.6.3/bill-statement-gen-0.1.0.0/x/bill-statement-gen-exe/build/bill-statement-gen-exe/bill-statement-gen-exe /usr/bin/bill-statement-gen-exe
ADD failed: stat /var/lib/docker/tmp/docker-builder029745061/root/project/dist-newstyle/build/x86_64-linux/ghc-8.6.3/bill-statement-gen-0.1.0.0/x/bill-statement-gen-exe/build/bill-statement-gen-exe/bill-statement-gen-exe: no such file or directory
Exited with code 1
```
