### ISSUE TITLE
extra-build-args not interpolating value from environment variable

### ISSUE THREAD

**Issue by abishek-antwalk** [CircleCI-Public/aws-ecr-orb#192]
### Orb version

8.1.0

### What happened

We use build args to pass arguments into the container build process. These  arguments are then used during docker build.

In our CircleCI job, we do the following:

```
version: 2.1
orbs:
  node: circleci/node@4.7
  aws-ecr: circleci/aws-ecr@8.1.0

workflows:
  build-and-deploy-dev:
    jobs:
        - aws-ecr/build-and-push-image:
            repo: ${AWS_REPO_NAME}
            region: ${AWS_DEFAULT_REGION}
            tag: ${CIRCLE_SHA1}
            aws-cli-version: latest
            dockerfile: Dockerfile.dev
            extra-build-args: |
             --build-arg AWS_ACCESS="${AWS_ACCESS_KEY_ID}" --build-arg AWS_SECRET="${AWS_SECRET_ACCESS_KEY}"
            filters:
              branches:
                only:
                  - dev
                  - circleci-project-setup
```

In 8.1.0, the build fails because the value of AWS_ACCESS_KEY_ID is taken as `$AWS_ACCESS_KEY_ID` and AWS_SECRET_ACCESS_KEY as `$AWS_SECRET_ACCESS_KEY`. instead of the actual values.

### Expected behavior

extra-build-args should interpolate the values of the keys from the environment variable for the project

`--build-arg AWS_ACCESS=AKIA****** --build-arg AWS_SECRET=cpQ******4a`

**Comment by manishparanjape** [comment]
Any update on this? I am also facing the same issue.

**Comment by hongyihu** [comment]
Hi, this is also a problem when passing in environment variables as parameters. For example, if I want to set `path` as `<<parameters.path>>` where the default is `$CIRCLE_JOB`, then `path` is interpreted as `$CIRCLE_JOB` instead of the actual value.

**Comment by manishparanjape** [comment]
I have created a Pull Request. This should also fix the issue reported by hongyihu.
I have no way of testing my changes so please review and merge if this works.

**Comment by KyleTryon** [comment]
https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=8.1.1

v8.1.1 has been released. Thank you @manishparanjape

**Comment by swiknaba** [comment]
> https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=8.1.1
> 
> v8.1.1 has been released. Thank you @manishparanjape

I tried to upgrade from 7.x to 8.1.3 and this is still broken.

> adoring_kowalevski
> error: "docker buildx build" requires exactly 1 argument.
> See 'docker buildx build --help'.
> 
> Usage:  docker buildx build [OPTIONS] PATH | URL | -
> 
> Start a build
> 
> Exited with code exit status 1


```
      - aws-ecr/build-and-push-image:
          repo: << pipeline.parameters.project-name >>
          tag: commit-${CIRCLE_SHA1}
          extra-build-args: --build-arg GIT_SHA="${CIRCLE_SHA1}" --build-arg FOO="$FOO"
          path: backend
          remote-docker-version: '20.10.18'
```
