### ISSUE TITLE
role-arn not interpolating value from project environment variable

### ISSUE THREAD

**Issue by zbroniszewski** [CircleCI-Public/aws-ecr-orb#194]
**NOTE**: I have opened this issue as well with the `aws-cli` orb [here](https://github.com/CircleCI-Public/aws-cli-orb/issues/105), because I'm currently unsure where the root cause resides; whether it is due to the way `aws-ecr` is collecting/passing the `role-arn` parameter to the `aws-cli` orb, or if the issue is merely with the `aws-cli` orb.

### Orb version
8.1.0

### What happened
We are using the `circleci/aws-ecr@8.1.0` orb, which is using the `circleci/aws-cli@3.1` orb.  
We are using the `build-and-push-image` command of the `aws-ecr` orb, and based on our configuration of this command, this uses the `role-arn-setup` command of the `aws-cli` orb.

When attempting to pass a Project environment variable to the `role-arn` parameter of the `build-and-push-image` command of the `aws-ecr` orb, which is also passed as the `role-arn` parameter of the `role-arn-setup` command of the `aws-cli` orb, this environment variable is not interpolated. Instead, it is processed plain, which results in the following error message during execution of the `ecr-login.sh` script of the `aws-ecr` orb (since this is executed subsequent to the `role-arn-setup.sh` script of the `aws-cli` orb, which did not provide an interpolated `role-arn` in the AWS profile):

`Parameter validation failed: Invalid length for parameter RoleArn, value: 19, valid min length: 20`

We've used SSH debugging in CircleCI to determine that the role arn of the role profile is indeed not interpolated, instead it looks something like this:
```
[profile example-role]
role_arn = ${ABC_AWS_ROLE_ARN}
source_profile = example-user
```
Or this (When we try different interpolation methods):
```
[profile example-role]
role_arn = $ABC_AWS_ROLE_ARN
source_profile = example-user
```

I've done my best to track, in order, how the `role-arn` is passed and used between these orbs in our exact scenario/configuration:
1. https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/commands/build-and-push-image.yml#L34
2. https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/commands/build-and-push-image.yml#L242
3. https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/commands/ecr-login.yml#L23
4. https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/commands/ecr-login.yml#L108
5. https://github.com/CircleCI-Public/aws-cli-orb/blob/master/src/commands/role-arn-setup.yml#L26
6. https://github.com/CircleCI-Public/aws-cli-orb/blob/master/src/commands/role-arn-setup.yml#L41
7. https://github.com/CircleCI-Public/aws-cli-orb/blob/master/src/scripts/role-arn-setup.sh#L6

### CircleCI Configuration
```yaml
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.0

executors:
  builder:
    docker:
      - image: cimg/base:stable
    resource_class: large

workflows:
  build_and_push_php_image:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: ABC_AWS_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: ABC_AWS_SECRET_ACCESS_KEY
          create-repo: false
          dockerfile: .docker/abc/Dockerfile
          executor: builder
          extra-build-args: --target dist --compress
          new-profile-name: example-role
          path: src/
          platform: linux/amd64
          profile-name: example-user
          public-registry: false
          push-image: true
          region: $AWS_REGION
          registry-id: AWS_ECR_REGISTRY_ID
          remote-docker-layer-caching: true
          remote-docker-version: 20.10.12
          repo: $AWS_ECR_PHP_REPO_NAME
          role-arn: ${ABC_AWS_ROLE_ARN}
          role-session-name: $CIRCLE_JOB
          session-duration: '1200'
          setup-remote-docker: true
          skip-when-tags-exist: false
          source-profile: example-user
          tag: $CIRCLE_WORKFLOW_ID
```

### Expected behavior
role-arn is interpolated from Project environment variable, and interpolated variable is properly set in AWS config profile
