### ISSUE TITLE
Multiple tags per image

### ISSUE THREAD

**Issue by Vlaaaaaaad** [CircleCI-Public/aws-ecr-orb#20]
### Orb version

3.0.0

### What happened

Currently images can only have 1 tag as per your example due to [how the job is written](https://github.com/CircleCI-Public/aws-ecr-orb/blob/3e435388beb8a9abdc2c2369fbf8b6ac44cff8ab/src/commands/build-image.yml#L44):
```
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0

workflows:
  complete_build_and_push:
    jobs:
      - aws-ecr/build_and_push_image:
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          region: AWS_REGION_ENV_VAR_NAME
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          repo: myECRRepository
          # ECR image tag, defaults to "latest"
          tag: ${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
```

### Expected behavior

There is a desire for an image to have multiple tags, in our case both the `${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}`, the `${CIRCLE_SHA1}`, and say `latest`.

```
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0

workflows:
  complete_build_and_push:
    jobs:
      - aws-ecr/build_and_push_image:
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          region: AWS_REGION_ENV_VAR_NAME
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          repo: myECRRepository
          tag: [ ${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}, ${CIRCLE_SHA1}, "latest"]
```

This is currently blocked by https://ideas.circleci.com/ideas/CCI-I-701 which asks for list parameters to be enabled.

Are there any workaround for this?
