### ISSUE TITLE
Docker Layer Cache

### ISSUE THREAD

**Issue by ToldoDM** [CircleCI-Public/aws-ecr-orb#202]
Hi can someone please help me with docker layer caching?
I've tried to use like specified on the Orb site, but i still didn't figured out how to have docker layer caching.
I'm currently using a free plan that has the feature for the DLC (is no longer required to have Performace or better).
Also I've already contacted the support to let me activate DLC.

Every time i set another run, the docker start downloading again and again. The whole workflow take about 25m of which the build process take about 15-18 min, so I'm trying desperately to use DLC.

this is my current file:
```version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  aws-ecs: circleci/aws-ecs@2.2.1

workflows:
  build-and-deploy:
    jobs:
      - build-and-push-image
      - aws-ecs/deploy-service-update: # create a new task definition
          requires:
            - build-and-push-image
          container-image-name-updates:  # name of the container defined in the task definition
          cluster-name: # ECS cluster name
          family: # name of the task definition's family.
          service-name: # name of the service
          force-new-deployment: true

jobs:
  build-and-push-image:
    docker:
      - image: cimg/base:2021.04 # CircleCI base Ubuntu-based image
    steps:
      - aws-ecr/build-and-push-image:
          remote-docker-layer-caching: true
          setup-remote-docker: true
          repo: a_repo
          tag: a_tag
          no-output-timeout: 15m # 10 minutes could let to workflow stop
```

### Orb version
8.1.2

### What happened

Didn't cache the docker layers

### Expected behavior

Cache the docker layers

**Comment by jpdsteno** [comment]
Same here. DLC is a no go. This is a deal breaker for me.

**Comment by alexgorb2016** [comment]
Hi, Is it possible to fix this issue?

**Comment by jrinaudo** [comment]
Same here, I have:
```
jobs:
  build-and-push-docker-image:
    executor:
      name: aws-ecr/default
      use-docker-layer-caching: true
    steps:
      - ...
      - aws-ecr/build-and-push-image:
          repo: test-repo
          tag: "$GIT_SHA1"
```
But it's not using layer caching.

**Comment by kelvintaywl** [comment]
Hi folks!

thank you for reaching out here, and sharing on this issue.

I understand from similar posts ([one example here](https://discuss.circleci.com/t/does-docker-layer-caching-support-buildx/41401/2)) and after trying myself indeed that:

- Docker Layer Cache (DLC) is not working somehow with `docker buildx build` command.

This is relevant here, because:

- as of aws-ecr Orb v8.x (from [v8.0.0](https://github.com/CircleCI-Public/aws-ecr-orb/pull/172) onwards), the orb [uses `docker buildx build` to build the Docker images](https://github.com/CircleCI-Public/aws-ecr-orb/pull/172/files#diff-a8c26089aa7f4921d1453f53ccef2ec03e47a8f6e71090273790dc6feb14023cL1)

I believe folks facing issues around DLC "misses" because of the above.

As such, I think there are 2 possible solutions / workarounds for now:

1. use the Orb at a version < 8.0.0, in this case, [v7.3.0](https://circleci.com/developer/orbs/orb/circleci/aws-ecr?version=7.3.0), _or_
2. "construct"/modify the aws-ecr/build-and-push-image job to update your job to use `docker build` (without buildx) instead

For (1), this is the easiest option, and works well for most use-cases I believe.
**However, this may not be an option if** you are using some of v8.x features like using AWS IAM role.

For (2), this may be a little tricky.
If you are comfortable writing your own shell scripts, you can of course forgo using the Orbs and write your own commands.
However, I understand that is not ideal, and there is a reason why we are using & relying on Orbs like this here.

I was able to craft a working example, where I utilized the docker orb and this aws-ecr Orb to build & push my image to AWS ECR with DLC!
Here is the [working build](https://app.circleci.com/pipelines/github/kelvintaywl-cci/whale-this-work/14/workflows/e0e45635-dcbd-45b6-ba9b-6d294055c184/jobs/63?invite=true#step-105-84), where you can see the DLC hit:
<img width="823" alt="Screen Shot 2022-08-26 at 12 32 51" src="https://user-images.githubusercontent.com/2164346/186811851-2f2173c3-6c84-4a8c-9dca-f8a47e6d78a2.png">


Here is the [config](https://github.com/kelvintaywl-cci/whale-this-work/blob/a3709454b73d5e895bfc7fcfacaffab01b7a7efc/.circleci/config.yml), for sharing:

```yaml
version: 2.1

orbs:
  docker: circleci/docker@2.1.3
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  publish:
    parameters:
      image:
        type: string
      tag:
        type: string
        default: "${CIRCLE_SHA1}"
      registry:
        type: string
        default: docker.io
      aws-public-registry:
        type: boolean
        default: false
      aws-registry-id:
        type: env_var_name
        default: AWS_ECR_REGISTRY_ID
      aws-region:
        type: string
        default: "${AWS_REGION}"
    executor:
      name: docker/machine
      dlc: true
    steps:
      - checkout
      - aws-ecr/ecr-login:
          public-registry: << parameters.aws-public-registry >>
          registry-id: << parameters.aws-registry-id >>
          region: << parameters.aws-region >>
      - docker/build:
          image: << parameters.image >>
          tag: << parameters.tag >>
          registry: << parameters.registry >>
      - docker/push:
          image: << parameters.image >>
          tag: << parameters.tag >>
          registry: << parameters.registry >>

workflows:
  use-docker-orb:
    jobs:
      - publish:
          image: "kelvintaywl/fancy-nginx"
          tag: "orb-${CIRCLE_SHA1}"
          registry: "public.ecr.aws/z1j6a2i1"
          aws-public-registry: true
          aws-region: ap-northeast-1
```

**Note**: In my case, I am pushing to AWS public ECR.
You may want to adapt accordingly to your needs then!

Hope this helps to explain the situation, and provide some next steps!
