### ISSUE TITLE
Docker Layer Caching Not Working

### ISSUE THREAD

**Issue by nategoethel** [CircleCI-Public/aws-ecr-orb#205]
### Orb version

v8.1.2

### What happened

Docker layer caching does not seem to be working. I expect to see cache hits after the first build, but I don't.

My CircleCI config looks like this:
```yaml
executors:
  build:
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true

jobs:
  Build Images:
    executor: build
    steps:
      - git-shallow-clone/checkout
      - run:
          name: Enable BuildKit
          command: export DOCKER_BUILDKIT=1
      - aws-ecr/build-and-push-image: # one for each image/repo
          aws-access-key-id: AWS_ACCESS_KEY
          aws-cli-version: latest
          aws-secret-access-key: AWS_SECRET_KEY
          dockerfile: Dockerfile
          #extra-build-args: '--cache-from type=local,src=/home/circleci/docker-cache --cache-to type=local,dest=/home/circleci/docker-cache,mode=max'
          no-output-timeout: 20m
          path: ./worker/
          platform: linux/amd64
          public-registry: false
          push-image: true
          region: us-east-2
          registry-id: AWS_ECR_REGISTRY_ID
          repo: worker
          skip-when-tags-exist: false
          tag: '$CIRCLE_SHA1'
```

### Expected behavior

If the executor used with the orb has DLC enabled, cache hits should be seen on subsequent runs.
