### ISSUE TITLE
Multi-stage docker builds fail

### ISSUE THREAD

**Issue by dolphub** [CircleCI-Public/aws-ecr-orb#21]
### Orb version
3.0.0

### What happened
Docker build fails with multi-stage copy

```
 ---> ff87c2f09e67
Removing intermediate container c0803b11e91c
Step 24/28 : COPY --from=build-prod /usr/src/app/node_modules /usr/src/app/node_modules/
COPY failed: stat /var/lib/docker/overlay2/7afb654f56fa9ec29e75fc7b8b8d24285408646a63bd1a34a6ce395c848447e8/merged/usr/src/app/node_modules: no such file or directory
Exited with code 1
```
### Expected behavior

I may not be understanding this properly... perhaps there is something to do with the executor used with this build to not have a docker engine that supports multi-stage build commands / functionality?  

Here is my config.yml

```
orbs:
  aws-ecr: circleci/aws-ecr@3.0.0
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          repo: ${AWS_ECR_REPO_NAME}
          tag: testing-alpha.0
```

**Update**
I've added the recommended following `/` to the path names for copying folders, same issue.
