### ISSUE TITLE
[jobs:build-and-push-image] An error occurred (ValidationError) when calling the AssumeRoleWithWebIdentity operation: Request ARN is invalid

### ISSUE THREAD

**Issue by kangaechu** [CircleCI-Public/aws-ecr-orb#211]
### Orb version

8.1.2

### What happened

When authenticating using CircleCI OIDC Token, the `Generate shotlived AWS Keys using CircleCI OIDC token` step displays the error message `An error occurred (ValidationError) when calling the AssumeRoleWithWebIdentity operation: Request ARN is invalid`.
The process itself completes successfully, but it appears that the AWS access token (AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN) is not obtained correctly.

```yaml
workflows:
  jobs:
    test:
      - aws-ecr/build-and-push-image:
          registry-id: AWS_ACCOUNT_ID
          region: ${AWS_REGION}
          assume-web-identity: true
          role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/test
          role-session-name: test
          context: aws-oidc
          tag: test-${CIRCLE_SHA1}
          repo: test/test
```

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/989985/173960486-164b0cef-f8e2-4733-ba16-8de67bd8d557.png">

### Expected behavior

Obtain an AWS access token (AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN) using CircleCI OIDC Token.

### How to fix 

This issue is the same as https://github.com/CircleCI-Public/aws-cli-orb/issues/106.
This bug has been fixed in circleci/aws-cli@3.1.1

circleci/aws-ecr@8.1.2 uses Orb from circleci/aws-cli@3.1.

https://github.com/CircleCI-Public/aws-ecr-orb/blob/v8.1.2/src/%40orb.yml#L11

So updating to circleci/aws-cli@3.1.1 will fix this problem.
