### ISSUE TITLE
[jobs:build-and-push-image] cat: /home/circleci/.docker/config.json: No such file or directory

### ISSUE THREAD

**Issue by kangaechu** [CircleCI-Public/aws-ecr-orb#213]
### Orb version

8.1.2

### What happened

In build-and-push-image job, `Log into Amazon ECR with profile default` step returns error message like `cat: /home/circleci/.docker/config.json: No such file or directory`.
But this step ends sussessfully.

```yaml
  jobs:
    test:
      - aws-ecr/build-and-push-image:
          registry-id: AWS_ACCOUNT_ID
          region: ${AWS_REGION}
          assume-web-identity: true
          role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/test
          role-session-name: test
          context: aws-oidc
          tag: test-${CIRCLE_SHA1}
          repo: test/test
```

### Expected behavior

This message is not displayed.
