### ISSUE TITLE
Create-repo fails if repo exists

### ISSUE THREAD

**Issue by gujo** [CircleCI-Public/aws-ecr-orb#22]
### Orb version
3.0.0

### What happened
When running a job with create-repo: true the job will fail on the second run because the repo already exists.

```
aws --region $AWS_REGION ecr create-repository --repository-name dummy-service --profile default

An error occurred (RepositoryAlreadyExistsException) when calling the CreateRepository operation: The repository with name 'dummy-service' already exists in the registry with id 'xxxxxxxxxxx'
Exited with code 255
```

### Expected behavior
According to the documentation the repo should be created _if it does not exist,_  this would mean that the RepositoryAlreadyExistsException should be ignored.

**Comment by psoares-resilient** [comment]
Would be keen to see a fix for this soon

**Comment by peermuellerxw** [comment]
This could do the job:

```  
- when:
      condition: <<parameters.create-repo>>
      steps:
        - run: >-
            command: |
               aws ecr describe-repositories --region $<<parameters.region>> --repository-names <<parameters.repo>> > /dev/null 2>&1 || \
               aws --region $<<parameters.region>> ecr create-repository --repository-name <<parameters.repo>> --profile <<parameters.profile-name>>
```
