### ISSUE TITLE
Using 8.1.2 orb to create ecr with buildx to use ARM64 architecture is not working.

### ISSUE THREAD

**Issue by heberrealself** [CircleCI-Public/aws-ecr-orb#224]
I'm trying to generate and push an ECR image using aws-ecr@8.1.2 with ARM64 architecture but when I try the execution I'm stuck with an error ocurring at the https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/scripts/docker-buildx.sh script.  The error says "`ERROR: "docker buildx build" requires exactly 1 argument.`".  This is in the last command of the sh script.  

```
docker --context builder buildx build \
      -f "${PARAM_PATH}"/"${PARAM_DOCKERFILE}" \
      ${docker_tag_args} \
      --platform "${PARAM_PLATFORM}" \
      --progress plain \
      "$@" \
      "${PARAM_PATH}"
```

All previous commands are executed correctly, below is the part of my yaml file that is calling the sh script.

```
- aws-ecr/build-and-push-image:
               extra-build-args: '--build-arg ssh_prv_key="$(base64 ~/.ssh/id_rsa)" --build-arg ssh_pub_key="$(base64 ~/.ssh/id_rsa.pub)"'
               registry-id: AWS_ECR_REGISTRY_ID
               aws-access-key-id: ACCESS_KEY_ID
               aws-secret-access-key: SECRET_ACCESS_KEY
               region: 'AWS_REGION'
               platform: linux/arm64
               profile-name: CIRCLECI_NAME
               repo: REPO_NAME
               skip-when-tags-exist: false
               tag: 'latest'
```

Am I missing a parameter?  I already review all the documentation about it but could not found the problem.
