### ISSUE TITLE
pushing multi platform image into public ecr repo

### ISSUE THREAD

**Issue by KunWoong** [CircleCI-Public/aws-ecr-orb#228]
### Orb version
8.1.2 

### What happened

when build and push image to public repo with more than one parameters for platform, it says
"AWS ECR does not support multiple platforms for public registries. Please specify only one platform and try again"

```
if [ "${PARAM_PUBLIC_REGISTRY}" == "1" ]; then
    if [ "$arch_count" -gt 1 ]; then
        echo "AWS ECR does not support multiple platforms for public registries. Please specify only one platform and try again"
        exit 1
     fi

    ECR_COMMAND="ecr-public"
    PARAM_ACCOUNT_URL="public.ecr.aws/${!PARAM_REGISTRY_ID}"
fi
```

Below is my pseudo job

```
 - aws-ecr/build-and-push-image:
          tag: latest
          repo: repo_name
          dockerfile: Dockerfile
          public-registry: true
          setup-remote-docker: true
          remote-docker-layer-caching: true
          remote-docker-version: 20.10.11
          platform: linux/amd64,linux/arm64
```

### Expected behavior

what i expect is, push like 'docker buildx build --platform linux/amd64,linux/arm64'
