### ISSUE TITLE
8.2.1 build-and-push-image job does not have build-path parameter added

### ISSUE THREAD

**Issue by SasakiYuta-mf** [CircleCI-Public/aws-ecr-orb#257]
Thanks for aws-ecr-orb.

### Orb version

8.2.1

### What happened

build-and-push-image job does not have build-path parameter added.

In the following example:
```
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
          build-path: "test"
```

A validation error occurs.
```
❯❯❯ circleci config validate
Error: Error calling workflow: 'build-and-deploy'
Error calling job: 'aws-ecr/build-and-push-image'
Unexpected argument(s): build-path
```

Build-and-push-image command can use the build-path parameter.

PR(https://github.com/CircleCI-Public/aws-ecr-orb/pull/251) in version 8.2.0 seems to have added a build-path parameter to the docker-build-and-push-image command and job. However, there were no changes to the [jobs/build-and-push-image.yml](https://github.com/CircleCI-Public/aws-ecr-orb/pull/251/files).

### Expected behavior

The build-path can be passed as a parameter.
The validation command succeeds.
