### ISSUE TITLE
Unable to build ARM image

### ISSUE THREAD

**Issue by flipsed** [CircleCI-Public/aws-ecr-orb#262]
### Orb version

8.2.1

### What happened

I'm getting the following error when trying to build an image:
```
+ docker --context builder buildx build -f ./Dockerfile -t ********************************************/**************:none --platform linux/amd64,linux/arm64 --progress plain --load --build-arg PCLOUDKEY=************************************************ .
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 2.0s done
#1 creating container buildx_buildkit_silly_williamson0
#1 creating container buildx_buildkit_silly_williamson0 0.7s done
#1 DONE 2.7s
ERROR: docker exporter does not currently support exporting manifest lists

Exited with code exit status 1

CircleCI received exit code 1
```

with this config:
```
     [...]
      - aws-ecr/build-and-push-image:
          repo: api-base-image
          push-image: false
          skip-when-tags-exist: false
          tag: 'none'
          aws-access-key-id: REPO_AWS_ACCESS_KEY_ID
          aws-secret-access-key: REPO_AWS_SECRET_ACCESS_KEY
          registry-id: AWS_ACCOUNT_ID
          extra-build-args: |
            --build-arg "PCLOUDKEY=${PCLOUDKEY}"
```

### Expected behavior

Do not add the `--load` flag to the `docker buildx build` command when the `--platform` flag contains multiple platforms (as per https://github.com/docker/buildx/issues/59#issuecomment-616061869)
