### ISSUE TITLE
unknown shorthand flag: 'f' in -f when Running with Docker Version 20 or earlier

### ISSUE THREAD

**Issue by colinbjohnson** [CircleCI-Public/aws-ecr-orb#263]
### Orb version

`aws-ecr: circleci/aws-ecr@8.2.1`

### What happened

When running on a [CircleCI self-hosted runner](https://circleci.com/execution-environments/runner/) with Docker version 20.x (i.e. a CircleCI runner using either Ubuntu 22, Amazon Linux 2, Amazon Linux 2022) we get the following error when running a 

```
+ docker buildx build -f ././Dockerfile -t ************.dkr.ecr.*********.amazonaws.com/org/test:test --platform linux/amd64 --progress plain --push .
unknown shorthand flag: 'f' in -f
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND
```

### Expected behavior

I would expect that the orb work on a [CircleCI self-hosted runner](https://circleci.com/execution-environments/runner/) with the Docker Version provided by Amazon Linux 2 when using a `yum` or `amazon-linux-extras` install. I could not find an "out of the box" mechanism for installing Docker version 21 or newer.

### Other Notes

- the orb works correctly with Docker version 21 or version 23 installed (so, presumably, all versions > 21)

**Comment by paulipotter** [comment]
I'm having the same issue. Apologies for the noob question but how can I choose what docker version to use?

**Comment by toini** [comment]
I had the same issue and realized that the problem was my custom ci image didnt buildx plugin (https://github.com/docker/buildx) installed. Solution was to switch to cimg/base image and install my custom stuff on it.

**Comment by jazmon** [comment]
We're experiencing this same error with the ubuntu machine executor, we have the image version set to `ubuntu-2004:202010-01`

**Comment by toini** [comment]
@jazmon how about if you try to use `cimg/base:current`?

**Comment by brivu** [comment]
Hey @colinbjohnson and @jazmon. 

Thanks for opening this. I am trying to reproduce your issue but I can't seem to. I've tested this on my end and found that `docker buildx` will work on `Docker` version`19.03` or newer [according to their repo](https://github.com/docker/buildx#installing)

I've tried using your same image to run the `build-and-push` job and get the same failure.

I've checked the version of `Docker` on `ubuntu-2004:202010-01` and I'm not sure why version `19.03.13` doesn't work

```
Client: Docker Engine - Community
 Version:           19.03.13
...
Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
```



**However, if I use `ubuntu-2204` the command works and the `Docker` version is:** 
```Client: Docker Engine - Community
 Version:           20.10.17
...
Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
```

**I'm using the 'image: ubuntu-2204:2022.07.1' as my executor for the following job:**

```
      - aws-ecr/build_and_push_image:
          name: integration-tests-default-profile
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::122211685980:role/CPE_ECR_OIDC_TEST
          attach_workspace: true
          workspace_root: workspace
          repo: aws-ecr-orb-${CIRCLE_SHA1:0:7}-default-profile
          create_repo: true
          context: [CPE_ORBS_AWS]
          dockerfile: sample/Dockerfile
          executor: ubuntu2204
          post-steps:
            - run:
                name: "Check Docker Version"
                command: docker version
```

If you're able to use and updated version of `ubuntu` this orb should work. In the meantime, I'll add some notes to our documentation. 

Thanks you! 
Brian

**Comment by brivu** [comment]
Hey @paulipotter, 

Thanks for letting me know. 
> I'm having the same issue. ~Apologies for the noob question but how can I choose what docker version to use?~ EDIT: I found answer (sorta) [here](https://circleci.com/docs/building-docker-images/#docker-version). I'm still unsure on how to work around this
> 
> ```
> - setup_remote_docker:
>     version: 20.10.11
> ```
> 
> but it seems setup remote docker doesn't accept any versions later than 20.10.18

In your example above, the `version` parameter is a string. Can you try wrapping `20.10.11` with double quotes? Docker version 20 should work with `docker buildx`

I've also tested your issue using `setup_remote_docker` along with the `cimg/python:3.8` image as my executor in a job. 
I ran the `build-and-push` command and was able to get everything working. I used your version of Remote Docker:  `20.10.11`

Here's the job I ran:

```
- aws-ecr/build_and_push_image:
    name: integration-tests-default-profile
    attach_workspace: true
    setup_remote_docker: true
    remote_docker_version: "20.10.11"
    workspace_root: workspace
    repo: aws-ecr-orb-${CIRCLE_SHA1:0:7}-default-profile
    create_repo: true
    context: [CPE_ORBS_AWS]
    dockerfile: sample/Dockerfile
    path: workspace
    executor:python3.8
    post-steps:
      - run:
          name: "Check Docker Version"
          command: docker version
```

I was able to build and push an image with this job. When checking the Docker version, I received the following output: 

```
Client: Docker Engine - Community
 Version:           20.10.22
...
Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
```

Hope that helps! Let me know if you have other issues!

Best, 
Brian
