### ISSUE TITLE
Invalid length for parameter RoleArn [WebIdentity]

### ISSUE THREAD

**Issue by Pitta** [CircleCI-Public/aws-ecr-orb#266]
### Orb version

aws-ecr@8.2.1

### What happened

I am getting this error today trying to pivot to this orb from bespooke shell calls.

```
Parameter validation failed:
Invalid length for parameter RoleArn, value: 16, valid min length: 20
Failed to assume role
```

We use a context + OIDC to talk to AWS

### Expected behavior

the orb to pick up the correct role arn supplied by the context env var and continue to build and push the container.

### Notes

Seems to be similar to https://github.com/CircleCI-Public/aws-ecr-orb/issues/203
I'd be happy with knowing what version has worked this way that I can pin to until this seems to settle down.

**Comment by brivu** [comment]
Hey @Pitta. Thank you for opening this issue. In a couple of weeks, we will release a major version `9.0` of this orb. One of the changes is that we will no longer import the `aws-cli` orb automatically which will eliminate compatibility issues with dependent orbs. 

Having said that, the latest version will require you to import the `aws-cli` orb into your `config.yml` file. In addition, the latest version of this orb will introduce the `auth` parameter, requiring authentication through the `aws-cli/setup` command. 

While testing `v9.0`, I included a test for your use case. I stored the `role_arn` as an environment variable `CircleCI > Project Settings > Environment Variables`. I passed  the the variable similarly to the original comment (`'${ECR_ROLE_ARN}'` and it worked fine. 

Here's an example of my job: 
```
- aws-ecr/build_and_push_image:
          name: integration-tests-default-profile
          auth:
            - aws-cli/setup:
                role_arn: '${ECR_ROLE_ARN}'
          attach_workspace: true
          workspace_root: workspace
          repo: aws-ecr-orb-${CIRCLE_SHA1:0:7}-default-profile
          create_repo: true
          context: [CPE_ORBS_AWS]
```

Give this a try when we release the latest version and let me know if you still have any issues. 

Best, 
Brian
