### ISSUE TITLE
`aws-ecr/build_and_push_image` should be able to be used as a command

### ISSUE THREAD

**Issue by ozooxo** [CircleCI-Public/aws-ecr-orb#29]
### Orb version

3.1.0

### What happened

If I use `aws-ecr/build_and_push_image` in `workflows` as a "job", then everything goes fine.

```
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      ...
      - aws-ecr/build_and_push_image:
      ...
```

However, if I use it as a "command" in my customized job, I'll get error messages.

```
jobs:
  - qa-deploy:
    docker:
      - image: circleci/postgres:11
        environment:
          POSTGRES_PASSWORD: postgres

    steps:
      - checkout
      - aws-ecr/build_and_push_image:
      ...

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      ...
      - qa-deploy
```

```
#!/bin/sh -eo pipefail
# Error calling workflow: 'build-test-and-deploy'
# Error calling job: 'qa-deploy'
# Cannot find a definition for command named aws-ecr/build_and_push_image
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
Exited with code 1
```

### Expected behavior

I think it will be nice if `aws-ecr/build_and_push_image` can be used as a command. By doing so we can hide the detailed steps in my customized job, rather than showing a bloated list of steps in my workflow.

Notice that it is supported by `circleci/aws-s3` https://circleci.com/orbs/registry/orb/circleci/aws-s3

```
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  build:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - checkout
      - run: mkdir bucket && echo "lorum ipsum" > bucket/build_asset.txt
      - aws-s3/sync:
          from: bucket
          to: 's3://my-s3-bucket-name/prefix'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
      - aws-s3/copy:
          from: bucket/build_asset.txt
          to: 's3://my-s3-bucket-name'
          arguments: '--dryrun'
```

**Comment by iynere** [comment]
@ozooxo it doest exist as a command:

https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/commands/build-and-push-image.yml

confusingly, it has a slightly different name. i'll push a commit so the names match.

**Comment by iynere** [comment]
ok, give it a shot w/ version `4.0.2`—both the command & the job are now called `build-and-push-image` @ozooxo

**Comment by rob4629** [comment]
Hey,

I'm not sure if I'm using the command incorrectly, however I keep hitting a Build Error: `Cannot find a definition for command named aws-ecr/build_and_push_image`


```
commands:
   build_and_push_image_to_ecr:
     description: "Build Docker image and push to ECR"
     steps:
       - aws-ecr/build_and_push_image:
           account-url: ${AWS_ECR_ACCOUNT_URL}
           create-repo: true
           repo: ${SERVICE_REPO}
           tag: $CIRCLE_SHA1


jobs:
push_to_ecr:
     parallelism: 1
     working_directory: ~/my/dir
     docker:
       - image: ruby:2.4.1-stretch
       
     steps:
       - checkout
       - run:
           name: build my image
           command: docker build --target my_image_base
       - build_and_push_image_to_ecr

workflows:
  version: 2.1
      - push_to_ecr:
```

I've also tried calling it directly from the Job with the same result.
