### ISSUE TITLE
Cannot use command interpolation in tag parameters

### ISSUE THREAD

**Issue by KnutFr** [CircleCI-Public/aws-ecr-orb#298]
### Orb version

Issue incoming with this commit https://github.com/CircleCI-Public/aws-ecr-orb/commit/9632aa04a1d515422cb53a1b3df7ce1c787c1acd#diff-27420d37ce437f88af6c5acf291dbd88ecc4f48c6add4d18e44d99e4ab589941L4 

I've spot it on v9.0.0 

### What happened

Since the parameters tag isn't evaluated anymore, we cannot inject command anymore for it. 
We use to inject a cat reading output file from our semver steps : 

``` 
          tag: `$(cat ./app-version)`
```

Now this input cause this error : 
```
+ docker buildx build -f ./apps/todd/Dockerfile -t '********************************************/todd-api:$(cat' './app-version)' --platform linux/amd64 --progress plain --build-arg NPM_TOKEN --push .
error: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Start a build

Exited with code exit status 1
```

### Expected behavior

The tag parameters should be evaluated so the behavior don't change with this version.

**Comment by dev-whoan** [comment]
Any updates on it?

I have a similar issue for calculating the tag.

```
# Let's assume that, `CIRCLE_SHA1` is `1234567890abcdef`.

parameters:
  my_tag: ${CIRCLE_SHA1:0:10} # should return 1234567890

aws-ecr/build_and_push_image:
  tag: << parameters.my_tag >>
```

However, the result docker image tag looks like `1234567890abcdef`.

**Comment by dev-whoan** [comment]
nvm. I just found the PR #307  related this issue.

**Comment by hamishdh** [comment]
I also ran into this issue upgrading to `aws-ecr@9.0.1` as I was creating the tag from the `git rev-list` for our [Flux CD](https://fluxcd.io/flux/guides/sortable-image-tags/#formats-and-alternatives). 

The PR linked by @dev-whoan looks like the proper fix, but if anyone is looking for a quick _hacky_ workaround then the below might work for you.
The `auth` parameter can run overloaded to run arbitrary commands, so I'm using it to construct an env var that is used in the `tag` parameter. My job looks something like this now:

```yaml
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup
            - run:
                name: Setup ECR Tag Environment Variable
                command: echo 'export ECR_TAG="$(git rev-parse --short $CIRCLE_SHA1)-$(git rev-list --count $CIRCLE_SHA1),latest"' >> "$BASH_ENV"
          tag: ${ECR_TAG} # Use the tag created in the auth step
          ....
```
