### ISSUE TITLE
Producing zero-size image on machine image ubuntu-2204:current

### ISSUE THREAD

**Issue by vatima2016** [CircleCI-Public/aws-ecr-orb#300]
### Orb version
9.0.0
machine image: ubuntu-2204:current

### What happened
After updating from 8.2.1 to 9.0.0 there are generated one image index,  one zero-size image and one non-zero-size image.
![aws-ecr-orb 2023-08-24 a las 10 45 56](https://github.com/CircleCI-Public/aws-ecr-orb/assets/17909224/04679afd-010f-496f-976e-cf2cbd22cac6)

Old usage:
```
# 8.2.1 - image tag 0.6.3-8433
- aws-cli/setup:
    role_arn: <<parameters.role_arn>>
- aws-ecr/build-and-push-image:
    repo: <<parameters.repo>>
    create-repo: false
    platform: <<parameters.platform>>
    skip-when-tags-exist: false
    dockerfile: <<parameters.dockerfile>>
    tag: <<parameters.tag>>
    no-output-timeout: 20m
    checkout: false
    attach-workspace: false
    workspace-root: ~/project
    registry-id: AWS_ACCOUNT_ID
```
New usage:
```
# 9.0.0  - image tag 0.6.3-8466
- aws-ecr/build_and_push_image:
    repo: <<parameters.repo>>
    create_repo: false
    platform: <<parameters.platform>>
    auth:
      - aws-cli/setup:
          role_arn: <<parameters.role_arn>>
    skip_when_tags_exist: false
    dockerfile: <<parameters.dockerfile>>
    tag: <<parameters.tag>>
    no_output_timeout: 20m
    checkout: false
    attach_workspace: false
    workspace_root: ~/project
```
Where:
```
platform: linux/arm64
machine:
    image: ubuntu-2204:current
      docker_layer_caching: true
    resource_class: arm.medium
```

### Expected behavior
As far as the image should be generated for the only platform I'd expect either the old behaviour producing the only image without any index or at least one index and one non-zero-size image.

### Workaround
Pin machine image version to ubuntu-2204:2022.07.1
