### ISSUE TITLE
build_extra_arg adds extra single quotes

### ISSUE THREAD

**Issue by nicoalonsop** [CircleCI-Public/aws-ecr-orb#303]
### What happened
The following worked on `8.2.1`
```
steps:
  - add_ssh_keys:
      fingerprints:
        - "<fingerprint>"
  - aws-ecr/build_and_push_image:
      auth:
          - aws-cli/setup:
              role_arn: "$AWS_ROLE_ARN"
      repo: my_repo
      tag: ${CIRCLE_SHA1},latest
      extra_build_args: --ssh default=~/.ssh/id_rsa_<fingerprint>
```
It fails with the following error.
```
docker buildx build ... --progress plain --ssh 'default=~/.ssh/id_rsa_<fingerprint>' ...
error: stat ~/.ssh/id_rsa_<fingerprint>: no such file or directory
```
I confirmed that the file exists by adding a step between `add_ssh_keys` and the `build_and_push_image` ( `ls ~/.ssh/id_rsa_<fingerprint>`) 
I connected to the job and ran `docker build ...` without the `'`  that are wrapping `default=~/.ssh/id_rsa_<fingerprint>` and it worked.

### Expected behavior

I expect it to run smoothly.
