### ISSUE TITLE
Profile name not set when calling aws ecr put-lifecycle-policy

### ISSUE THREAD

**Issue by toini** [CircleCI-Public/aws-ecr-orb#311]
### Orb version

9.0.1

### What happened

When attempting to set an ECR repository lifecycle policy by calling

```
  - aws-ecr/build_image:
      profile_name: shared-services
      lifecycle_policy_path: ./aws/default-lifecycle-policy.json
      ...
```

We end up executing this command at https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/scripts/docker_buildx.sh#L57:
```
      aws ecr put-lifecycle-policy \
        --repository-name "${ORB_EVAL_REPO}" \
        --lifecycle-policy-text "file://${ORB_EVAL_LIFECYCLE_POLICY_PATH}"
```

Note that the profile name is not passed as a command line parameter. This results in error:
```
Unable to locate credentials. You can configure credentials by running "aws configure".
Exited with code exit status 253
```

### Expected behavior

AWS profile name should be passed and put-lifecycle-policy command should be succesfully executed.
