### ISSUE TITLE
extra_build_args: No Support for Docker Options that contain spaces (Example: --build-arg BUILD_DATE=$(date +%F))

### ISSUE THREAD

**Issue by colinbjohnson** [CircleCI-Public/aws-ecr-orb#313]
## What would you like to be added

I (and a client we work with) would like the ability to use `extra_build_args` options that contain spaces (`--build-arg BUILD_DATE=$(date +%F)`). An example is shown below:

```yaml
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.1
  aws-cli: circleci/aws-cli@4.1.1

workflows:

  version: 2

  build-and-push-image:
    jobs:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup
          context: cloudavail-test
          dockerfile: ./Dockerfile
          extra_build_args: >-
            --build-arg BUILD_DATE=$(date +%F)
          repo: cloudavail/cache-invalidation-test
          tag: ${CIRCLE_SHA1}
```

## Why is this needed

I feel like this is needed as users of the AWS ECR Orb may want to pass Docker Options that contain spaces. 

## Problem Reproduction

A CircleCI file like:

```
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.1
  aws-cli: circleci/aws-cli@4.1.1

workflows:

  version: 2

  build-and-push-image:
    jobs:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup
          context: cloudavail-test
          dockerfile: ./Dockerfile
          extra_build_args: >-
            --build-arg BUILD_DATE=$(date +%F)
          repo: cloudavail/cache-invalidation-test
          tag: ${CIRCLE_SHA1}
```

Which returns the following error

```shell
+ docker buildx build -f ././Dockerfile -t ************.dkr.ecr.*********.amazonaws.com/cloudavail/cache-invalidation-test:2d273d59c4b708cd057720a889002c8e79eec399 --platform linux/amd64 --progress plain --build-arg 'BUILD_DATE=$(date' '+%F)' --push .
error: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -
```

## Errata

It feels like "extra_build_args" should be named `extra_build_options`. I would understand if this change is not considered or not considered until a newer version of the AWS ECR Orb is released.

In regards to naming the string passed to `extra_build_args` is described as ["Extra flags to pass to docker build" ini the CircleCI orb documentation](https://circleci.com/developer/orbs/orb/circleci/aws-ecr#jobs-build_and_push_image) and as considered "Options" in the Docker documentation.
