### ISSUE TITLE
`workspace-root` does not support anything which is not `.`

### ISSUE THREAD

**Issue by ozooxo** [CircleCI-Public/aws-ecr-orb#32]
### Orb version

3.1.0

### What happened

```
jobs:
  java-build:
    executor: java-with-postgres-executor

    steps:
      - checkout
      ...
      - persist_to_workspace:
          root: /tmp/java-build
          paths:
            - docker/web/*.war

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      ...
      - aws-ecr/build_and_push_image:
          checkout: true
          attach-workspace: true
          workspace-root: /tmp/java-build
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: /tmp/java-build/docker/web/Dockerfile
          path: /tmp/java-build/docker/web
          region: AWS_DEFAULT_REGION
          repo: "ecs-circleci-qa-repository"
          tag: "${CIRCLE_SHA1}"
```

I got 

```
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/java-build/docker/web/Dockerfile: no such file or directory
Exited with code 1
```

https://circleci.com/gh/gitenter/gitenter/388

but change to `.` the job succeed.

```
      - aws-ecr/build_and_push_image:
          checkout: true
          attach-workspace: true
          workspace-root: .
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: ./docker/web/Dockerfile
          path: ./docker/web
          region: AWS_DEFAULT_REGION
          repo: "ecs-circleci-qa-repository"
          tag: "${CIRCLE_SHA1}"
```

https://circleci.com/gh/gitenter/gitenter/393

### Expected behavior

If it is equivalent to 

```
    working_directory: /tmp/java-build
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/java-build
```

`workspace-root` should support arbitrary path rather than just `.`.
