### ISSUE TITLE
Similar bug to https://github.com/CircleCI-Public/aws-ecs-orb/issues/206

### ISSUE THREAD

**Issue by Sirafe** [CircleCI-Public/aws-ecr-orb#329]
### Orb version 
9.0.2

### What happened
Having the same issue with aws-ecr/build_and_push_image that the reporter for the ECS orb was having here with service_update and the ${CIRCLE_SHA1}  @ https://github.com/CircleCI-Public/aws-ecs-orb/issues/206
      - aws-ecr/build-and-push-image:
          checkout: false
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
                region: AWS_REGION
          dockerfile: Dockerfile-app
          path: ~/project
          repo: $repo
          push-image: false
          region: $region
          tag: ${CIRCLE_SHA1:0:7}

### Expected behavior
Using ${CIRCLE_SHA1:0:7} Should return only the first 7 characters of the hash. Instead it is returning the full hash.

### Additional Information
Expected behavior works with previous version 8.2.1

**Comment by hylaride** [comment]
@Sirafe  FWIW, we got around this by injecting the variables before the orb:

```YAML
    - setup_remote_docker
    - run:
        name: Get 7 digit git sha1
        command: |
          echo 'export SMALL_SHA="${CIRCLE_SHA1:0:7}"' >> "$BASH_ENV"
    - aws-ecr/build_and_push_image:
        - tag: ${SMALL_SHA}
```
