### ISSUE TITLE
pre-steps not working

### ISSUE THREAD

**Issue by perbergland** [CircleCI-Public/aws-ecr-orb#33]
### Orb version
4.0.1

### What happened
I tried to add pre-steps to the orb job as per the 2.1 documentation for jobs but the schema validation fails.

```
workflows:
  build:
    jobs:
      - test
      - build-bundle
      # https://github.com/CircleCI-Public/aws-ecr-orb
      - aws-ecr/build_and_push_image:
          repo: "my-container-registry"
          region: AWS_DEFAULT_REGION
          tag: "${CIRCLE_SHA1}"
          aws-access-key-id: AWS_ECR_USER_KEY
          aws-secret-access-key: AWS_ECR_USER_SECRET
          requires:
            - test
            - build-bundle
          pre-steps:
            - attach_workspace:
              at: bundle
```

I get this pretty unhelpful error

```
# ERROR IN CONFIG FILE:
# [#/jobs/aws-ecr~1build_and_push_image] only 1 subschema matches out of 2
# 1. [#/jobs/aws-ecr~01build_and_push_image/steps/0] 0 subschemas matched instead of one
# |   1. [#/jobs/aws-ecr~001build_and_push_image/steps/0] Input not a valid enum value
# |   |   Steps without arguments can be called as strings
# |   |     enum:
# |   |     - checkout
# |   |     - setup_remote_docker
# |   |     - add_ssh_keys
# |   2. [#/jobs/aws-ecr~001build_and_push_image/steps/0] extraneous key [at] is not permitted
# |   |   Permitted keys:
# |   |     - persist_to_workspace
# |   |     - save_cache
# |   |     - run
# |   |     - checkout
# |   |     - attach_workspace
# |   |     - store_test_results
# |   |     - restore_cache
# |   |     - store_artifacts
# |   |     - add_ssh_keys
# |   |     - deploy
# |   |     - setup_remote_docker
# |   |   Passed keys:
# |   |     []
```

### Expected behavior

If pre-steps would work I could actually use the orb job to attach some stuff from another job before building the docker image.
