### ISSUE TITLE
Image created is of type Image Index

### ISSUE THREAD

**Issue by AboulEinein** [CircleCI-Public/aws-ecr-orb#330]
### Orb version

v9.0.2

### What happened

```
      - aws-ecr/build_and_push_image:
          setup_remote_docker: true
          remote_docker_layer_caching: true
          auth:
            - aws-cli/setup:
          repo: 'repo'
          tag: '$CIRCLE_BUILD_NUM,latest'
```

I have the above code in my workflow, but for some reason I get 2 images pushed to ECR, one with a 0 size and no tags and the other one with the correct tags but it's Artifact Type is Image Index.
How can I change the behavior to have one image only, also the ECR scan is not running on the generated image because of it's type.

### Expected behavior

1 image to be created

**Comment by hylaride** [comment]
We also are getting the same noise added to our repos.  A workaround was to not to have `build_and_push_image` push the image, but have another `push_image` step, but 9.0.3 and 9.0.4 version of the orb [broke for us ](https://github.com/CircleCI-Public/aws-ecr-orb/issues/335)(we are now pinning 9.0.2).  

@AboulEinein FYI a workaround that works for us (if you pin to 9.0.2) is like I stated above and have `push_image: false` in `build_and_push_image` and then do this right after: 
```yaml
- aws-ecr/push_image:
        region: YOUR_REGION
        account_id: YOUR_ECR_ACCOUNT_ID
        repo: `repo`
        tag: '$CIRCLE_BUILD_NUM,latest'
```
