### ISSUE TITLE
All image builds broken until new release occurs

### ISSUE THREAD

**Issue by Andy-Bell** [CircleCI-Public/aws-ecr-orb#332]
### Orb version
All versions without [this commit ](https://github.com/CircleCI-Public/aws-ecr-orb/commit/21d867bfb13654f9655a928d32d0c3f9b449d40e)

### What happened
With the rolling brownouts, all deployments using this orb are failing as the image cannot be found

**Comment by dnoji** [comment]
@brivu Can you give an update on this one? Can you push another release with the referenced commit? This is creating some major issues for our workflows.

**Comment by gabrielqs** [comment]
seeing the same problems on our pipelines. can't setup any pipelines with DLC enabled on 9.0.3 (it doesn't allow me to setup remote docker on the docker executor) and i can't use 9.0.2 because its on a deprecated image.
i wonder how this deprecation happened so fast, even for circle. this has been disrupting all of our pipelines since this morning. and i assumed my pipelines were all safe knowing i was relying on almost up-to-date circleci orbs.

**Comment by mrj0** [comment]
Aw man, I was just here trying to update to 9.0.2 from 8 and having a bad time due to changes.. to find it won't actually fix my problem :-/

**Comment by drdaeman** [comment]
I'm not sure how it's broken - the referenced commit seems to only apply to an example YAML file (which, AFAIK, is not really used when using this orb) and a CI pipeline used to build this orb. There are no changes from `src/` outside of `src/examples/`.

FWIW, my pipelines using 8.2 version had somehow worked today. I've stumbled upon this issue looking for v9 upgrade docs, deciding to future-proof my CI config.

**Comment by Andy-Bell** [comment]
In case anyone is coming here because builds are broken due to the default executor image not being found, you can specify a custom executor for the build_and_upload job which you can specify using one of the approved images.

**Comment by VincentHuysmans1** [comment]
I'm migrating from v.8 to v.9.0.3. And keep getting following error: 

> ERROR: failed to solve: failed to push ************.dkr.ecr.eu-west-1.amazonaws.com/repo_name:latest: unexpected status from HEAD request to https://************.dkr.ecr.eu-west-1.amazonaws.com/v2/repo_name/blobs/sha256:ba7defbbdff31f315a3a0100a3ceb39362009ef0cc692b8eea469aaf3672a23b: 401 Unauthorized


When pushing the image to the ECR repository. I'm having a hard time trying to configure the latest version of the ecr orb. I use following config:


```
aws-ecr/build_and_push_image:
          name: build_push_lambda_dev
          auth:
            - aws-cli/setup:
                aws_access_key_id: MY_AWS_ACCESS_KEY_ID
                aws_secret_access_key: MY_AWS_SECRET_ACCESS_KEY
                profile_name: $MY_AWS_ACCOUNT_PROFILE_NAME
          attach_workspace: true
          workspace_root: "~"
          account_id: $MY_AWS_ACCOUNT_ID
          profile_name: $MY_AWS_ACCOUNT_PROFILE_NAME
          region: eu-west-1
          push_image: true
          tag: latest
          repo: repo_name
```

**Comment by cglango** [comment]
@Andy-Bell Can you give an example?

**Comment by Virtim** [comment]
Came here with a similar problem, though with another version of the orb. There is a parameter with which you can setup remote docker version which helps with resolving deprecation

For older version of the orb use this: `remote-docker-version: default`

With the current version (9.0.4) syntax has changed a bit so you should use `remote_docker_version: default`


A complete example of the build-and-push image step:
```
      - aws-ecr/build-and-push-image:
          repo: "repo"
          setup-remote-docker: true
          remote-docker-version: default
```

you can change `default` to other docker versions, you can find what options do you have in the documentation here: 
https://circleci.com/docs/remote-docker-images-support-policy/#release-policy
