### ISSUE TITLE
`no basic auth credentials` on push_image step

### ISSUE THREAD

**Issue by hylaride** [CircleCI-Public/aws-ecr-orb#335]
### Orb version
9.0.4 (Though this broke for me in 9.0.3 - 9.0.2 functions properly)

### What happened

push_image now fails on docker push to ECR with the following error:

```
a9db2aea91b3: Preparing 
2cea05c6512a: Preparing 
5498e8c22f69: Waiting 
no basic auth credentials

Exited with code exit status 1
```

### Expected behavior

Docker login should happen as before.  This is our orb instantiation:
```yaml
  steps:
    - setup_remote_docker
    - run:
        name: Get 7 digit git sha1
        command: |
          echo 'export SMALL_SHA="${CIRCLE_SHA1:0:7}"' >> "$BASH_ENV"
    - aws-ecr/build_and_push_image:
        auth:
          - aws-cli/setup:
              role_arn: $ECR_OID_ACCESS_ARN
              role_session_name: ecr-login
              profile_name: << parameters.repo >>-ecr-login
        profile_name: << parameters.repo >>-ecr-login
        account_id: "$AWS_ECR_REGISTRY_ID"
        no_output_timeout: << parameters.no-output-timeout >>
        region: << parameters.region >>
        repo: << parameters.repo >>
        skip_when_tags_exist: << parameters.skip-when-tags-exist >>
        tag: ${SMALL_SHA}
        path: << parameters.path >>
        push_image: false
    - aws-ecr/push_image:
        region: << parameters.region >>
        account_id: "$AWS_ECR_REGISTRY_ID"
        repo: << parameters.repo >>
        tag: ${SMALL_SHA}
```

I suspect [this pull request](https://github.com/CircleCI-Public/aws-ecr-orb/pull/327) is the culprit.  is there anything I need to change on my end to get the `aws-ecr/push_image` step to work?
