### ISSUE TITLE
E: The repository 'https://apt.kubernetes.io kubernetes-xenial Release' does not have a Release file.

### ISSUE THREAD

**Issue by Kunalkatdare** [CircleCI-Public/aws-ecr-orb#336]
config.yml

```
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      # Install dependencies
      - run:
          name: Install dependencies
          command: npm install
      # Run unit tests and allow 80% success
      - run:
          name: Run unit tests
          command: npm test || exit 0
  ecr-push:
    environment:
      AWS_ACCOUNT_ID: "xxxxxxxxxx"
    docker:
      - image: cimg/aws:2023.06
    steps:
      # - aws-cli/setup:
      #     role_arn: "arn:aws:iam::682010357027:role/circleci-oidc"
      - aws-ecr/build_and_push_image:
          account_id: ${AWS_ACCOUNT_ID}
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::xxxxxxxxxx:role/circleci-oidc
          create_repo: true
          repo: myECRRepository
workflows: 
  version: 2
  build_and_push:
    jobs:
      - build
      - ecr-push:
          requires:
            - build
```
