### ISSUE TITLE
Allow accessing registry of different account (--registry-id)

### ISSUE THREAD

**Issue by jakobmagiera** [CircleCI-Public/aws-ecr-orb#338]
## What would you like to be added

Currently the orb does not use the --registry-id parameter and defaults to the account id of the current account. We use a technical user that accesses the registry of a different account. The orb does not support this, so we had to manually run the aws ecr commands the orb uses internally, passing the --registry-id parameter.

## Why is this needed

This will allow working with a different account than the one the registry is contained in.

**Comment by nicoalonsop** [comment]
@jakobmagiera The orb is already using `--registry-id` parameter take a look to https://github.com/CircleCI-Public/aws-ecr-orb/blob/v9.0.4/src/scripts/docker_buildx.sh#L43

You will need to do something like the following:
```
version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-ecr: circleci/aws-ecr@9.0.3
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          account_id: ${ECR_AWS_ACCOUNT_ID}
          auth:
            - aws-cli/setup:
                << the corresponding values to log in to the account that does not contain the ECR  it could be with OIDC or keys>>
          skip_when_tags_exist: false
          tag: latest,myECRRepoTag

```
Could you share your config including the versions that you are using?
