### ISSUE TITLE
ECR login succeeds, but push fails with HEAD request 401 unauthorized

### ISSUE THREAD

**Issue by aoyama-val** [CircleCI-Public/aws-ecr-orb#345]
### Orb version

9.1.0

### What happened

```yaml
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@9.1.0
  aws-cli: circleci/aws-cli@4.1.3
workflows:
  build:
    jobs:
      - aws-ecr/build_and_push_image:
          context: *************
          repo: *************
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"
          auth:
            - aws-cli/setup:
              role_arn: ${AWS_IAM_ROLE_ARN}
```

```
#16 exporting to image
#16 exporting layers
#16 exporting layers 5.9s done
#16 exporting manifest sha256:6df314dcc346194eaf73963e15521ca9679586d95080a6efae886615b26306c0 0.0s done
#16 exporting config sha256:2069114fce5394cc9474b71dceb31fe1bbf781a27e349eeb61c8b7fa990f4a5e 0.0s done
#16 exporting attestation manifest sha256:d205a952b67cd4fd29396d25bbb4008368d2553bfbdb139a943572d1d7573b0d 0.0s done
#16 exporting manifest list sha256:d4b739fe2b3923dda7fe06893123cbfa061ef98eecf03d7dee037b7b414f281f 0.0s done
#16 pushing layers
#16 pushing layers 0.6s done
#16 ERROR: failed to push ************.dkr.ecr.**************.amazonaws.com/ticketing-rails:d4a654fb86a8e1c7ef4a912c49a96a73921aaea7: unexpected status from HEAD request to https://************.dkr.ecr.**************.amazonaws.com/v2/ticketing-rails/blobs/sha256:1c656b3fb894779c46614514306b4b427ed930d4f4bddd8d085b475bc49263d3: 401 Unauthorized
------
 > exporting to image:
------

 2 warnings found (use --debug to expand):
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 2)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 12)
ERROR: failed to solve: failed to push ************.dkr.ecr.**************.amazonaws.com/*************:d4a654fb86a8e1c7ef4a912c49a96a73921aaea7: unexpected status from HEAD request to https://************.dkr.ecr.**************.amazonaws.com/v2/*************/blobs/sha256:1c656b3fb894779c46614514306b4b427ed930d4f4bddd8d085b475bc49263d3: 401 Unauthorized

Exited with code exit status 1
```

![スクリーンショット 2024-06-21 2 05 47](https://github.com/CircleCI-Public/aws-ecr-orb/assets/13144822/fdf41868-c7ec-4341-9b06-eb8477a93656)

### Expected behavior
Push succeeds.

**Comment by gonrial** [comment]
@aoyama-val can you check that the role stored in `AWS_IAM_ROLE_ARN` has permissions to push to that ECR repo?
If you have permissions, but it still not working, can you list the permissions associated to that role?

**Comment by aoyama-val** [comment]
The role has these permissions at least:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "ecr:BatchCheckLayerAvailability",
            "Resource": [
                "arn:aws:ecr:*****"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "ecr:CompleteLayerUpload",
                "ecr:UploadLayerPart",
                "ecr:InitiateLayerUpload",
                "ecr:PutImage",
                "ecr:BatchGetImage"
            ],
            "Resource": [
                "arn:aws:ecr:*****"
            ]
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": "ecr:GetAuthorizationToken",
            "Resource": "*"
        }
    ]
}
```

The config was working fine with aws-ecr@8.2.1 + aws-cli@3.1.4, however I faced the issue when tried to upgrade the orbs.

Thanks.

**Comment by aoyama-val** [comment]
I added Allow All permission to the role, but still push failed with the same error.
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Statement1",
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```

Also I changed the auth method from OIDC to access key/secret, and it worked fine. So I guess something about OIDC is wrong.

**Comment by gonrial** [comment]
@aoyama-val what is the definition for the role that you are using for OIDC? Pay special attention at the `Condition` section

**Comment by aoyama-val** [comment]
Carefully checked it but everything seemed correct. Also tried deleting the whole `Condition`, but nothing changed.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::XXXXXXXXXXXX:oidc-provider/oidc.circleci.com/org/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
            },
            "Action": "sts:AssumeRoleWithWebIdentity"
        }
    ]
}
```

**Comment by dgreda** [comment]
I'm facing the same problem. I've been using version 9.0.1 and it was working, but as soon as I upgraded to 9.1.0 it's no longer working. 

It happens on the attempt to push the image.

```
#10 ERROR: failed to push ************.dkr.ecr.*********.amazonaws.com/***: unexpected status from HEAD request to https://************.dkr.ecr.*********.amazonaws.com/v2/***: 401 Unauthorized
```

**Comment by dreik** [comment]
Same issue, starting v9.0.3

**Comment by sylwit** [comment]
Confirm downgrading to v9.0.1 fix the issue

**Comment by marboledacci** [comment]
This is more likely a problem with the aws-cli orb, could you do a aws-cli/setup command alone and validate the authentication worked?

You can do something like this:

```
- aws-cli/setup:
     role_arn: ${ROLE_ARN}
     post-steps:
            - run:
                name: "Validation"
                command: aws sts get-caller-identity
```

A combination of versions that should work using OIDC is: circleci/aws-cli@5.1.0 and circleci/aws-ecr-orb@9.3.0.
Please check if it works using these versions.

**Comment by sylwit** [comment]
https://github.com/CircleCI-Public/aws-ecr-orb/blob/master/src/commands/build_and_push_image.yml#L185

`auth:` shouldn't be required if it's already set previously.

**Comment by marboledacci** [comment]
@sylwit That's right, the auth shouldn't be required. Is that causing something related to his issue?

**Comment by b-jan** [comment]
Hello, we face the same issue trying to migrate from `circleci/aws-ecr@8.2` to `circleci/aws-ecr@9.3.2` with the new auth parameter.

`unexpected status from HEAD request... : 401 Unauthorized`

Did you guys find a fix?
We cannot understand how to do the migration correctly.

**Comment by marboledacci** [comment]
@b-jan how are you doing the authentication to ECR? Are you enabling credentials helper?

**Comment by jeandlv** [comment]
Thanks @marboledacci,

We fixed our issue by adding these parameters :

```
 use_credentials_helper: false
 extra_build_args: '--provenance=false'
```

We added ` extra_build_args: '--provenance=false'` to fix [this issue](https://stackoverflow.com/questions/77207485/why-are-there-extra-untagged-images-in-amazon-ecr-after-doing-docker-push).

**Comment by rafaelnogueira1** [comment]
@aoyama-val were you able to resolve this issue? I'm facing the same situation after updating.

**Comment by benmurden** [comment]
If you just want things to work the way they did before, wherever you use `aws-cli/setup`, explicitly export the credential values:
```yaml
- aws-ecr/build_and_push_image:
    auth:
      - aws-cli/setup:
          role_arn: arn:aws:iam::<account_id>:role/role_name
      - run:
          name: "Export AWS credentials"
          command: |
            echo "export AWS_ACCESS_KEY_ID=$AWS_CLI_STR_ACCESS_KEY_ID" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$AWS_CLI_STR_SECRET_ACCESS_KEY" >> $BASH_ENV
            echo "export AWS_SESSION_TOKEN=$AWS_CLI_STR_SESSION_TOKEN" >> $BASH_ENV
      - run:
          name: "Validation"
          command: aws sts get-caller-identity
...
```
### Explanation
This is due to changes in the `aws-cli` orb in which it no longer exports the environment variables with their standard names. It is supposed to set up a config profile instead, but for whatever reason that wasn't working for me. They also do this to prevent issues with multiple credentials in a single job, so if you need that, be aware this may mess things up.

I also added a validation step to make sure this is actually succeeding and not pushing the issue down the road after doing a whole Docker image build.

**Comment by Blue-Cheesecake** [comment]
Facing the same issue. (The acess key, secret key should not be a problem since I tried to push to ECR on my local device via these keys and it was successful but not in circleci)

```yaml
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.3.7
  aws-cli: circleci/aws-cli@5.1.2

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                aws_access_key_id: $AWS_ACCESS_KEY_ID
                aws_secret_access_key: $AWS_SECRET_ACCESS_KEY

          dockerfile: Dockerfile
          path: .
          repo: ***
          tag: $IMAGE_TAG_DEV
          platform: linux/arm64
```

**Comment by marboledacci** [comment]
@Blue-Cheesecake what exactly is your error?

**Comment by Blue-Cheesecake** [comment]
> [@Blue-Cheesecake](https://github.com/Blue-Cheesecake) what exactly is your error?

This 

```
#17 ERROR: failed to push *************************************************/project/name:*****: unexpected status from HEAD request to *********************************************************/v2/project/name/blobs/sha256:f12f82af4358d735f19464d18f9a42baa6cabcd70df461132c463c22f7b0fd87: 401 Unauthorized
------
 > exporting to image:
------
ERROR: failed to solve: failed to push *************************************************/watpomassage/dev/backend:*****: unexpected status from HEAD request to *********************************************************/v2/project/name/blobs/sha256:f12f82af4358d735f19464d18f9a42baa6cabcd70df461132c463c22f7b0fd87: 401 Unauthorized

Exited with code exit status 1

Exited with code exit status 1
```

<img width="1460" alt="Image" src="https://github.com/user-attachments/assets/25ed8858-f5b5-4e0e-ab98-1112b74d1875" />

**Comment by marboledacci** [comment]
@Blue-Cheesecake I think I finally found the problem for this, it is a problem with aws-cli orb, not with ecr orb, I created [this PR](https://github.com/CircleCI-Public/aws-cli-orb/pull/214) to solve it, when those changes are ready I'll notify you so you can test it again.

**Comment by marboledacci** [comment]
@Blue-Cheesecake the new release of aws-cli-orb is ready, version 5.1.3, try to use that and tell me if everything is good.

**Comment by marboledacci** [comment]
Is your context well setup? Please validate that the second step or your job _Preparing Environment Varialbes_ shows AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY.
And if you want be more precise with the validation, SSH into the instance and check the environment.

**Comment by Blue-Cheesecake** [comment]
> Is your context well setup? Please validate that the second step or your job _Preparing Environment Varialbes_ shows AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY. And if you want be more precise with the validation, SSH into the instance and check the environment to verify the value is correct.

Yes I already checked it and used these keys to push image on my local device to ECR.

<img width="1010" alt="Image" src="https://github.com/user-attachments/assets/f5f7028c-f345-495c-bb07-7276d052a735" />

<img width="1800" alt="Image" src="https://github.com/user-attachments/assets/79768c5b-c9ea-45f6-bfd5-a22e90fd38e9" />

<img width="1800" alt="Image" src="https://github.com/user-attachments/assets/52c35808-6ece-4305-b7db-fc1d7177fb93" />

**Comment by marboledacci** [comment]
In your examples I don't see you setting the context in the jobs, are you? I don't say the values are wrong, but are they part of your job?

**Comment by Blue-Cheesecake** [comment]
> In your examples I don't see you setting the context in the jobs, are you? I don't say the values are wrong, but are they part of your job?


I followed setting up environment variable via this doc [Set an environment variable in a project](https://circleci.com/docs/set-environment-variable/#set-an-environment-variable-in-a-project) . Once it set in project settings, I think it should be part of my job. 

I tried to check access key and secret key on CI like this 

```yaml
orbs:
  aws-ecr: circleci/aws-ecr@9.3.7
  aws-cli: circleci/aws-cli@5.1.3

jobs:
  test-env:
    docker:
      - image: cimg/node:18.11.0
    steps:
      - checkout
      - run:
          name: "Check Access Key"
          command: echo $AWS_ACCESS_KEY_ID
      - run:
          name: "Check Secret Key"
          command: echo $AWS_SECRET_ACCESS_KEY

workflows:
  build_and_push_image:
    jobs:
      - test-env:
          filters:
            branches:
              only: stg

      - aws-ecr/build_and_push_image:
          filters:
            branches:
              only: stg

          auth:
            - aws-cli/setup:
                aws_access_key_id: $AWS_ACCESS_KEY_ID
                aws_secret_access_key: $AWS_SECRET_ACCESS_KEY

          dockerfile: Dockerfile
          path: .
          repo: ****
          tag: $IMAGE_TAG_DEV
          platform: linux/arm64

```

Here's the result

![Image](https://github.com/user-attachments/assets/649dbf3d-b369-4347-861d-d0879be719ae) 

I believe they are part of my job or are there any extra steps I need to do?

(still the result of build and push image is failed with the same error)

![Image](https://github.com/user-attachments/assets/fde78013-1e65-4f40-846e-1e036558bfed)

**Comment by marboledacci** [comment]
You don't need to create a new job to validate that, just look in your job at the second step called _Preparing environment variables_, it would show you all the variables in your job.
I don't see anything wrong in your setup but it's good to be sure they are there. I've replicated your exact job several times and it keeps working, so my only idea is a problem in the environment variables.

**Comment by Blue-Cheesecake** [comment]
<img width="1432" alt="Image" src="https://github.com/user-attachments/assets/a6b6b071-2cbc-4f35-90b1-4ec8879f4a59" />

It seems they are part of environment variables.

**Comment by marboledacci** [comment]
Could you try disabling the credentials_helper? Set `use_credentials_helper` to false in the job.

**Comment by Blue-Cheesecake** [comment]
> Could you try disabling the credentials_helper? Set `use_credentials_helper` to false in the job.

Well finally it's work. Thanks!! 

```
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.3.7
  aws-cli: circleci/aws-cli@5.1.3

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          filters:
            branches:
              only: stg

          auth:
            - aws-cli/setup:
                aws_access_key_id: $AWS_ACCESS_KEY_ID
                aws_secret_access_key: $AWS_SECRET_ACCESS_KEY

          dockerfile: Dockerfile
          path: .
          repo: watpomassage/dev/backend
          tag: $IMAGE_TAG_DEV
          platform: linux/arm64
          use_credentials_helper: false
```
