### ISSUE TITLE
Version 6.0.0 - Cannot find a definition for job named aws-ecr/build_and_push_image

### ISSUE THREAD

**Issue by roger-king** [CircleCI-Public/aws-ecr-orb#35]
### What happened

When updating from the [example](https://circleci.com/docs/2.0/ecs-ecr/#build-and-push-the-docker-image-to-aws-ecr), 0.0.2 to 6.0.0. Circle is throwing an error:

```
Cannot find a definition for job named aws-ecr/build_and_push_image
```

### Expected behavior

Job should run.

my config:
```
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.0.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${AWS_REPO}"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"
```

**Comment by iynere** [comment]
the job is called `build-and-push-image @roger-king

**Comment by roger-king** [comment]
Thanks for that...

I am trying to now use `aws-ecr/build-image` and I am still getting `Cannot find a definition for job named aws-ecr/build-image`

```
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.0.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-image:
          account-url: AWS_ECR_URL
          repo: AWS_ECR_REPO
          region: AWS_DEFAULT_REGION
```
