### ISSUE TITLE
DLC_builder  but no append mode, specify the node name to make changes for existing instances

### ISSUE THREAD

**Issue by maheshevizio** [CircleCI-Public/aws-ecr-orb#358]
### Orb version   aws-ecr: circleci/aws-ecr@9.3.2

```
 version: 2.1
orbs:
  slack: circleci/slack@4.12.5
  aws-ecr: circleci/aws-ecr@9.3.2
  aws-cli: circleci/aws-cli@4.1.3


```
### What happened
The below error appears in CircleCI job need help to resolve it
```
  + docker buildx create --name DLC_builder --use
ERROR: existing instance for "DLC_builder" but no append mode, specify the node name to make changes for existing instances

Exited with code exit status 1

```
### Expected behavior

The job should pass through. We already referred this closed ticket and can't go back version 9.0.0 https://github.com/circleci-public/aws-ecr-orb/issues/308?ref=https://giter.site
