### ISSUE TITLE
Unable to specify a target image to build

### ISSUE THREAD

**Issue by rob4629** [CircleCI-Public/aws-ecr-orb#36]
### Orb version
6.0.0

### What happened
I'm trying to call the `build-and-push-image` job, but was wondering whether I can pass in a target image for the build step?

### Expected behavior
Essentially I’m using a multi-stage build in my Dockerfile, where the last image contains all of the test code. I would like to push the previous image to ECR, but can’t see how to do this using the `build-and-push-image` job.

```
commands:
  build_and_push_image_to_ecr:
    description: "Build Docker image and push to ECR"
    steps:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          create-repo: true
          repo: $SERVICE_REPO
          tag: $CIRCLE_SHA1
```

Would it be possible to specify a target image?
