### ISSUE TITLE
[bug] Error setting LifeCyclePolicy when `repo` name contains a `/` (namespace)

### ISSUE THREAD

**Issue by carlosjgp** [CircleCI-Public/aws-ecr-orb#368]
### Orb version

9.3.6
```
  aws-ecr: circleci/aws-ecr@9

```

### What happened

```
      - aws-ecr/build_and_push_image:
          checkout: false # we use the submodules checkout
          setup_remote_docker: true
          remote_docker_layer_caching: true
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::xxxxxx:role/my-role
                role_session_name: ${CIRCLE_PROJECT_REPONAME}
          account_id: $(aws sts get-caller-identity --query Account --output text)
          repo: hub/runtime
          platform: linux/amd64
          dockerfile: docker/ubuntu.Dockerfile
          extra_build_args: >-
            --build-arg VERSION=${VERSION}
            --target=release
          create_repo: true
          lifecycle_policy_path: .circleci/ecr-lifecycle-policy.json
          repo_policy_path: .circleci/ecr-repo-policy.json
          set_repo_policy: true
          repo_scan_on_push: true
          skip_when_tags_exist: true
          tag: ${tag1},${tag2},${tag3},${tag4}
```

Successfully sets the policy on the step

"Set Repository Policy"
```
{
    "registryId": "xxxxx",
    "repositoryName": "hub/runtime",
    "policyText": "{\n  \"Version\" : \"2012-10-17\",\n  \"Statement\" : [ {\n    \"Sid\" : \"AllowImagePull\",\n    \"Effect\" : \"Allow\",\n    \"Principal\" : {\n      \"AWS\" : \"*\"\n    },\n    \"Action\" : [ \"ecr:BatchCheckLayerAvailability\", \"ecr:BatchGetImage\", \"ecr:DescribeImages\", \"ecr:DescribeRepositories\", \"ecr:GetDownloadUrlForLayer\" ],\n    \"Condition\" : {\n      \"StringEquals\" : {\n        \"aws:PrincipalOrgID\" : \"yyyyyyy\"\n      }\n    }\n  } ]\n}"
}
```

But then fails to  set the policy (again) on the build stage for some reason

Build Docker Image with BuildX

```
An error occurred (RepositoryNotFoundException) when calling the PutLifecyclePolicy operation: The repository with name 'hub/runtime' does not exist in the registry with id 'xxxxxxxxx'

Exited with code exit status 254
```

### Expected behavior

ECR orb only sets the Lifecycle policy correctly and only does it once
