### ISSUE TITLE
Command `aws-ecr/build-and-push-image` should include `setup_remote_docker`

### ISSUE THREAD

**Issue by ozooxo** [CircleCI-Public/aws-ecr-orb#37]
### Orb version

6.0.0

### What happened

Right now by using `aws-ecr/build-and-push-image` as command, I got the following error in "Build docker image" step:

```
$ #!/bin/bash -eo pipefail
docker build \
   \
  -f ./docker/web/Dockerfile \
  -t $AWS_ECR_ACCOUNT_URL/qa-repository:${CIRCLE_SHA1} \
  ./docker/web
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Exited with code 1
```

https://circleci.com/gh/gitenter/gitenter/645

By adding `setup_remote_docker` things will pass with no problem.

```
  qa-deploy:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-ecr/build-and-push-image:
          ...
```

https://circleci.com/gh/gitenter/gitenter/647

### Expected behavior

It is kind of annoying for command user to `setup_remote_docker` themselves. It will be better if that step can just be included in the orb itself.

(Not sure if it relates to the docker image I am using. By using `circleci/python:2.7` things goes fine, but if I use `circleci/python:3.7.1` I fail the "Log into Amazon ECR" step.
