### ISSUE TITLE
Failed to build ARM image on different branch

### ISSUE THREAD

**Issue by chr1shung** [CircleCI-Public/aws-ecr-orb#384]
### Orb version
9.5.1

### What happened
I tried to build ARM image and push to ECR, the pipeline finished correct on `main` branch but failed on `dev` branch, here's the error:
```
dev: Pulling from *******
no matching manifest for linux/arm64 in the manifest list entries

Exited with code exit status 1
```

Below is my config:
```
version: 2.1
orbs:
  go: circleci/go@1.12.0
  aws-cli: circleci/aws-cli@5.1.2
  aws-ecr: circleci/aws-ecr@9.5.1

jobs:
  build-and-push:
    docker:
      - image: cimg/aws:2025.01
    resource_class: arm.medium
    steps:
      - checkout
      - setup_remote_docker:
        version: default
      - aws-ecr/build_image:
          account_id: ${AWS_ACCOUNT_ID}
          auth:
            - aws-cli/setup:
                role_arn: ${AWS_ROLE_ARN}
                region: ${AWS_DEFAULT_REGION}
                profile_name: ${AWS_PROFILE_NAME}
                role_session_name: build_and_push_image
          extra_build_args:
          platform: linux/arm64
          profile_name: ${AWS_PROFILE_NAME}
          push_image: false
          region: ${AWS_DEFAULT_REGION}
          repo: ${ECR_REPOSITORY_NAME}
          repo_scan_on_push: true
          skip_when_tags_exist: true
          tag: "${CIRCLE_SHA1},${CIRCLE_BRANCH}"

workflows:
  test-build-and-push:
    jobs:
      - build-and-push:
          context: my-ctx
```

### Expected behavior

The pipeline result should be the same no matter what branch the pipeline is running on.
Thanks for the help
