### ISSUE TITLE
Type check error when try to build using ecr version above 0.0.4

### ISSUE THREAD

**Issue by godlike0108** [CircleCI-Public/aws-ecr-orb#47]
### Orb version

Type check error happens when version is above 0.0.4.

### What happened

```
workflows:
  version: 2
  build:
      - aws-ecr/build_and_push_image:
          account-url: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
          repo: '${AWS_RESOURCE_NAME_PREFIX}'
          region: ${AWS_DEFAULT_REGION}
          tag: '${CIRCLE_SHA1}'
```
This is part of my CircleCI setup.
This works totally fine when version is below 0.0.4

Refer to this [issue#41](https://github.com/CircleCI-Public/aws-ecr-orb/issues/41), I changed orb job name to `aws-ecr/build-and-push-image` when I try to use `circleci/aws-ecr@6.2.0`

However this type check error always showed up when I try to build.
<img width="1515" alt="螢幕快照 2019-08-11 上午9 52 41" src="https://user-images.githubusercontent.com/22214574/62828633-d0859680-bc1d-11e9-9f18-3aa01572a00e.png">

What happened?

### Expected behavior

Build success like v0.0.4.

**Comment by lokst** [comment]
@godlike0108 In newer versions of the orb, some of the parameters are now of the type `env_var_name` instead of `string`. Could you try these changes? (You will need to define a new project env variable called AWS_ACCOUNT_URL or any name that you like) 

```
- aws-ecr/build_and_push_image:
          account-url: AWS_ACCOUNT_URL
          repo:  '${AWS_RESOURCE_NAME_PREFIX}'
          region: AWS_DEFAULT_REGION
          tag: '${CIRCLE_SHA1}'
```
