### ISSUE TITLE
Build fails on "Configure AWS Access Key ID" step

### ISSUE THREAD

**Issue by toymachiner62** [CircleCI-Public/aws-ecr-orb#49]
### Orb version

6.2.0

### What happened

My `.circle/config.yml` file:
```yml
orbs:
  aws-ecr: circleci/aws-ecr@6.2.0
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          region: AWS_REGION
          repo: myRepo
```
![image](https://user-images.githubusercontent.com/485782/63887047-87fe0500-c9a1-11e9-8d3c-9f36574dca03.png)

### Expected behavior

Build should get past this step.
