### ISSUE TITLE
Add support for --build-arg

### ISSUE THREAD

**Issue by FelixDuvalletKodiak** [CircleCI-Public/aws-ecr-orb#5]
Some Dockerfiles contain [arguments](https://docs.docker.com/engine/reference/builder/#arg):

    ARG SOME_ARG="default_value"

and are filled in during building: `docker build --build-arg SOME_ARG=my_value`

Can we add support for a list of build arguments in this orb?

**Comment by DanRoestorf** [comment]
@rauny-brandao What is the explanation on why this was closed? Build args are not working as documented.

Attempting to use build args like so:

```
      - aws-ecr/build_and_push_image:
          name: build-demo
          context: demo-global
          extra-build-args: 'VARIABLE=value'
          repo: 'demo'
```

Results in:

```
#!/bin/sh -eo pipefail
# Error calling workflow: 'build-deploy'
# Error calling job: 'aws-ecr/build_and_push_image'
# Unexpected argument(s): extra-build-args
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
Exited with code 1
```

**Comment by grking8** [comment]
Can someone confirm this works please with an example as I am struggling have tried various things e.g. 

`config.yml`

```
- aws-ecr/build_and_push_image:
          name: containerise-staging
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          region: $AWS_DEFAULT_REGION
          repo: mosaics/analytics-api
          tag: s
          extra-build-args: --build-arg GITHUB_SSH_RSA_PRIVATE_KEY=bye
```

`Dockerfile`

```
ARG GITHUB_SSH_RSA_PRIVATE_KEY=somedefault
RUN echo $GITHUB_SSH_RSA_PRIVATE_KEY
```

prints `somedefault` rather than `bye`

thanks for any help in advance
