### ISSUE TITLE
Set `tag` dynamically causes failure

### ISSUE THREAD

**Issue by toymachiner62** [CircleCI-Public/aws-ecr-orb#50]
### Orb version
6.3.0

### What happened
Build fails as version tagged locally is different than version trying to be pushed.

![image](https://user-images.githubusercontent.com/485782/64964539-ddbb2400-d860-11e9-9b88-309cff619fc7.png)

### Expected behavior
Tag should be the same

`.circle/config.yml`
```yml
orbs:
  aws-ecr: circleci/aws-ecr@6.3.0
version: 2.1

workflows:
  # Build and push to ECR on builds to master
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_REGION
          repo: node
          tag: $(date -u +"%Y-%m-%dT%H%M%SZ") # ISO 8601 date format
```

**Comment by lokst** [comment]
@toymachiner62 Thanks for reporting this. This is a case (dynamically evaluated tag value that evaluates to a different value during build and push) that version 6.3.0 does not handle. In the meantime, could you consider using a different way to compute a tag value? For example `$CIRCLE_BUILD_NUM` ?

**Comment by ankurjha21** [comment]
@lokst could you assign this to me I would love to contribute on it

**Comment by ankitjain28may** [comment]
@lokst Is there any way to define the variable globally?

**Comment by lokst** [comment]
@ankitjain28may Currently there's no straightforward way to do it, but putting the value in a file and attaching it to a workspace is one way to share it with downstream jobs.

**Comment by gmemstr** [comment]
One _could_ trigger a pipeline using our API to pass through pipeline parameters as well (https://circleci.com/docs/api/v2/#trigger-a-new-pipeline), which would eliminate the need to use a workspace file. This is how our own orbs trigger integration testing, since we need to publish a development version of an orb with the git commit hash in the version string. I'm not entirely sure this could be considered a bug with the orb, since it is behaving as expected.

**Comment by jf** [comment]
Thank you for coming up with this, @toymachiner62 . I didnt even think that we could have a dynamic tag this way!!

I've improved upon this and fixed the way to keep the tag constant between the build and push steps:

```
      - run:
          name: seed environment
          command: |
            echo $(date +%Y-%m-%d__%H-%M)__$(git log -n1 --format=%h) > IMAGE_TAG
      - aws-ecr/build-and-push-image:
          tag: $(cat IMAGE_TAG)
          ...
```

This works and gives you a stable tag in the environment. Really all you need is a a stable tag between "Build docker image" and "Push image to Amazon ECR". The format of the tag is entirely up to you, but I like having the datetime + hash reflected
