### ISSUE TITLE
Add Support For Buildkit

### ISSUE THREAD

**Issue by sampsonbryce** [CircleCI-Public/aws-ecr-orb#77]
## What would you like to be added

Docker 19.03 now supports buildkit which can be activated by setting the environment variable `DOCKER_BUILDKIT=1` before running the `docker build` command. https://docs.docker.com/develop/develop-images/build_enhancements/

I have not found a way to do this so I am assuming it is not possible with the current orb. Correct me if I'm wrong please :)

## Why is this needed

Buildkit significantly decreases build times and allows for better secret management via the --secret command line argument

**Comment by sampsonbryce** [comment]
I figured out how to do this. You need to explicitely tell circle to give you the right version of docker that supports buildkit. The default one (at the time of writing) does not allow buildkit. You cannot use the `setup-remote-docker` param on the orb commands because it doesn't allow you to specify the docker version so you just do it yourself before you call the command. 

You can find docker version that the setup_remote_docker command supports here: https://circleci.com/docs/2.0/building-docker-images/#docker-version

Here is an example of my setup:

```yaml
build-api:
    docker:
      - image: circleci/python:3.8
    environment:
      DOCKER_BUILDKIT: "1"

    steps:
      - checkout

      - setup_remote_docker:
          version: 18.09.3

      - aws-ecr/build-and-push-image:
          account-url: <ACCOUNT_URL_VAR_NAME>
          aws-access-key-id: <ACCESS_KEY_ID_VAR_NAME>
          aws-secret-access-key: <SECRET_ACCESS_KEY_VAR_NAME>
          dockerfile: Dockerfile
          region: <ECR_REGION_VAR_NAME>
          repo: <REPO>
          tag: "latest"
```
