### ISSUE TITLE
Base build image from private ecr to push to another ecr

### ISSUE THREAD

**Issue by tomas-stefano** [CircleCI-Public/aws-ecr-orb#81]
### Orb version

6.7.0

### Description

I am changing my app to use a base build image from a aws ecr private repo and then after running everything pushes the app image to another ecr.

I read the documentation in using private aws ecr [here](https://circleci.com/docs/2.0/private-images/) and everything worked on the apps that don't use the orb to push to another instance. The only one that uses the orb it fails as I show below.

My .circleci/config.yml file:

```yaml
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

jobs:
  test:
    working_directory: ~/circle
    docker:
      - image: $AWS_BUILD_IMAGE_ECR_ACCOUNT_URL
        aws_auth:
          aws_access_key_id: $AWS_BUILD_IMAGE_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_BUILD_IMAGE_SECRET_ACCESS_KEY
# .... run tests, deployment stuff, etc
workflows:
  version: 2
  release:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          name: push_app_image
          dockerfile: Dockerfile
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_DEFAULT_REGION
          repo: "name-of-the-repo"
          tag: "APP_${CIRCLE_SHA1}"
```

### What happened

This is the error that raises in the beginning of the CI:

```
error authentication with ECR: UnrecognizedClientException: The security token included in the request is invalid.
	status code: 400
```

I already verified **a lot of times** the env values of AWS_BUILD_IMAGE_ECR_ACCOUNT_URL and 
AWS_ECR_ACCOUNT_URL and the values are okay as I can login using the `aws` cli for each different ecr.

#### Why am I posting here?

The reason that I am posting here is that all the other repositories which I use the build image passes in the CircleCI and only this particular app that use this orb does not pass so I wonder how can I achieve what I want to achieve.

#### Main questions

Is this a bug? Sorry if this is not the right place to post this issue.

I know the orbs looks for default env vars like `AWS_ECR_ACCOUNT_URL` so I wonder if CircleCI  is looking to `AWS_ECR_ACCOUNT_URL` as well for the base image instead of looking for `AWS_BUILD_IMAGE_ECR_ACCOUNT_URL` (the right one that I specified). 

The next step that I will try is to change "AWS_ECR_ACCOUNT_URL" to something else but I feel that I should raise this issue in case someone already had or will have this issue too.

Any thoughts?

**Comment by tomas-stefano** [comment]
The interesting part is that if I change the orb to:

```
      - aws-ecr/build-and-push-image:
          name: push_app_image
          dockerfile: Dockerfile
          account-url: $AWS_PUSHED_IMAGE_ECR_ACCOUNT_URL
          aws-access-key-id: $AWS_PUSHED_IMAGE_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_PUSHED_IMAGE_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          repo: "name-of-the-repo"
          tag: "APP_${CIRCLE_SHA1}"
```

Then getting the build image (solves the problem above) but then it generates another error:

Spin the environment works and solves the problem above:

```
#  Spin Up Environment √
```

But then it generates another problem:

```
# Type error for argument aws-access-key-id: expected type: env_var_name, actual value: \"${AWS_PUSHED_IMAGE_ACCESS_KEY_ID}\" (type string)
# Type error for argument account-url: expected type: env_var_name, actual value: \"${AWS_PUSHED_IMAGE_ECR_ACCOUNT_URL}\" (type string)
# Type error for argument aws-secret-access-key: expected type: env_var_name, actual value: \"${AWS_PUSHED_IMAGE_SECRET_ACCESS_KEY}\" (type str
```

So a conflict is definitely happening and it look like a bug to me.

### What should happen

The build step should use the base build private ecr image and then build and deploy to the other ecr instance, both specified in the yaml file.

Again, any thoughts on it?
