### ISSUE TITLE
Docker build error - invalid argument "/*****************:latest" for t: invalid reference format

### ISSUE THREAD

**Issue by temidevops** [CircleCI-Public/aws-ecr-orb#83]
### Orb version
6.7.0

### What happened

build-and-deploy is failing on "build docker image":

```
#!/bin/bash -eo pipefail
docker_tag_args=""
IFS="," read -ra DOCKER_TAGS <<< "latest"
for tag in "${DOCKER_TAGS[@]}"; do
  docker_tag_args="$docker_tag_args -t $AWS_ECR_ACCOUNT_URL/temi-web-platform:$tag"
done
docker build \
   \
  -f ./Dockerfile \
  $docker_tag_args \
  .
`

`invalid argument "/*****************:latest" for t: invalid reference format
See 'docker build --help'.
```

Config:

```     
aws-ecr/build-and-push-image:
          executor: default_exec
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_REGION
          repo: temi-web-platform
          tag: latest
          requires:
            - test
          context: temi-web-platform-global
          filters:
            branches:
              only:
                - integration
                - dev-aviram
```

Link to failing build: https://app.circleci.com/jobs/github/ROBOTEAM-HOME/web-platform/42

### Expected behavior

Docker build completes successfully.
