### ISSUE TITLE
 AWS ECS URL parameter is redundant

### ISSUE THREAD

**Issue by ExternalReality** [CircleCI-Public/aws-ecr-orb#84]
## What would you like to be added

 the URL can be derived directly from the region and the account id. The orb, already having requesting the region as a parameter, should simply request the account_id and construct the url internally form that information.

```
 - aws-ecr/build_and_push_image:
          account-account-id: account_id #use account_id not explicit URL
          repo: repo_name
          region: region
```

The above is enough information to construct the url.

https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html

# Why is this needed

This makes the Orb interface easier and more DRY by limiting errors and redundant information.
